### ISSUE TITLE
Some thumbnails are offset and shrunk in the library view.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1046]
I'm sure this is already known, but I couldn't find it, so recording it here.

![thumbnail-bug.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/a58aa170-c92a-40c5-85c2-6b70ace5beda/thumbnail-bug.gif)

**Comment by thisandagain** [comment]
Thanks @chrisgarrity I'll take this one.

**Comment by paulkaplan** [comment]
@fsih posted this on the possibly related 
![image](https://user-images.githubusercontent.com/654102/34681458-f5d88910-f469-11e7-97cd-f3c3ae3dfbf0.png)

**Comment by paulkaplan** [comment]
@thisandagain here is the situation: The library thumbnails are just displaying the SVG directly, so it will show with whatever bounds are written into the SVG. The cake SVG has bounds that are messed up. You can tell by putting a border around the `svg` element: here is a comparison of the "good" cake vs the "bad" cake.

![cake-bounds](https://user-images.githubusercontent.com/654102/34730432-653b3140-f52d-11e7-8560-d9a5fc80847a.gif)

A few things can cause this to happen. I know opening some svgs in illustrator and resaving them can cause the bounds to change a lot. Uploading an svg to scratch, making a modification and resaving it can also change the bounds.

Since I don't think we want to have to pass library thumbnails through any kind of rendering step, we probably just want the SVGs to have the desired bounding boxes.

**Comment by thisandagain** [comment]
@paulkaplan Ok. This is a pretty tremendous amount of manual work to resolve. I think we should discuss finding a UROP to help resolve this as it seems unlikely I'll have time.

**Comment by fsih** [comment]
The SVG renderer code is already automating this adjustment. I think we could use it to output adjusted SVGs

**Comment by paulkaplan** [comment]
These look like they have been resolved. Closing
