### ISSUE TITLE
Broadcast blocks in palette lock mouse pointer

### ISSUE THREAD

**Issue by khanning** [LLK/scratch-gui#1047]
### Expected Behavior

Click the drop down menu on a broadcast block in the palette and see the dropdown menu.

### Actual Behavior

Click the drop down menu on a broadcast block in the palette and the mouse pointer becomes locked to either the palette scroll bar or the block itself.

### Steps to Reproduce

1. Create a new project
2. Before dragging out any broadcast blocks, click on a drop down
 menu on any of the broadcast blocks from the palette
3. Either the palette scrollbar or the block itself become "attached" to the mouse pointer

![broadcastbug](https://user-images.githubusercontent.com/1169507/34058023-9012f996-e1a7-11e7-9bc2-c3a9d9d20f10.gif)

### Operating System and Browser

Mac OS 10.11.6 Chrome 63.0.3239.84

**Comment by mrjacobbloom** [comment]
Could be related to LLK/scratch-blocks#1270

**Comment by kchadha** [comment]
This was caused by [this change in scratch-blocks](https://github.com/LLK/scratch-blocks/commit/2c078544e773e914fb3a408182c3ff076d939263), and has a patch in the changes in PR [LLK/scratch-blocks#1302](https://github.com/LLK/scratch-blocks/pull/1302).

What's happening here is that when the dropdown menu is clicked on a broadcast block from the flyout, there are no menu options to populate the dropdown menu with.
