### ISSUE TITLE
Adjusting trim handles while previewing a sound does not effect the playback 

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1109]
### Expected Behavior
I'd expect the newly trimmed area to take effect on the playback. There is a question of when to make that determination:
1. When the trim handle is dropped (mouse-up) after being dragged
2. Where ever the handle is regardless of it being dragged or after being dropped

We observed in a workshop that 2 was the expectation, but that may be rather complex on the technical side. 

### Actual Behavior
This is rather nuanced to describe in words, but if you adjust the handles while playing a sound, the playback ignores the newly set trimming.

![trimming](https://user-images.githubusercontent.com/3409578/34271751-ae1e0aa8-e65b-11e7-887d-03eaf10ce9d6.gif)
 
### Steps to Reproduce
1. Add or Record a longer sounds
2. Play the sound
3. Adjust the trim handles

### Operating System and Browser

OS: macOS 10.11.6
Browser: Chrome Version 63.0.3239.84

**Comment by supertopoz** [comment]
@carljbowman It's been a while since you added this. 

I'm taking a look at your enhancement to see if I can help. I fully understand your case 2.  

I am working towards a possible solution for that, but I'm wondering about a possible case 3. What if the player just stopped whenever the first slider or the second slider are moved during play back, would this work also?

**Comment by paulkaplan** [comment]
Trim handles do not exist anymore, closing!
