### ISSUE TITLE
Expose Blockly and VM

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#120]
### Expected Behavior

_They would be exposed/accessible to JavaScript console_

### Actual Behavior

_They VM is not and Blockly is extremely scaled down._

### Steps to Reproduce

_Go to the playground and open JavaScript console_

**Comment by Airhogs777** [comment]
I'd be for more hackability, the more customizable the better. I'd rather be able to modify the editor through a userscript than having to fork the whole project

**Comment by rschamp** [comment]
I would argue that this issue should really be about the fact that these are available in the global namespace at all, because it should be confined only to the components that need to interact with them. Hacking on the VM and scratch-blocks is not the purpose of this repo, it's to build the UI components that interact with them.

If you install the [React Developer Tools](https://facebook.github.io/react/blog/2015/09/02/new-react-developer-tools.html), you can have access to the internals of the components, such as the VM, renderer, etc.

Making the GUI accessible to userscripts is a different issue altogether.

**Comment by TheBrokenRail** [comment]
Should I make a issue about makin the UI accessible for user scripts?

**Comment by rschamp** [comment]
Sure!
