### ISSUE TITLE
What should GUI display if 'something terrible' happens

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1205]
To handle the WebGL errors, I've added an [error boundary](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html). If the failure is WebGL it'll show the missing WebGL modal, but what should it display if something unexpected fails.

**Comment by thisandagain** [comment]
First pass on copy for January (we should make this look nice in February):
```
Headline: Oops! Something went wrong.
Body: We are so sorry, but it looks like Scratch has crashed. This bug has been automatically reported to the Scratch Team. Please refresh your page to try again.
```

**Comment by thisandagain** [comment]
@chrisgarrity Rather than close this, can you move to February and assign @carljbowman once you get this copy in?

**Comment by carljbowman** [comment]
Here is a quick proposal for this state. It uses all the current copy and minimal CSS, but feels a little more intentional.

![v2 - general oops](https://user-images.githubusercontent.com/3409578/36676230-11d6b32c-1ad9-11e8-8dca-bbb2fb1fdee8.png)

Asset: [Reload Icon](https://github.com/LLK/scratch-gui/files/1758987/reload.svg.zip)

If it's helpful, here is a diagram of the flow that was discussed last week. This shows all the other moving parts of the system. Happy to answer any questions.
![v3_load flow](https://user-images.githubusercontent.com/3409578/36676842-b302393c-1ada-11e8-9ffe-cfeb50cf383a.png)

**Comment by thisandagain** [comment]
@chrisgarrity Is this something you could prioritize? Currently this piece of the flow is blocking @kchadha 's "import from 2.0" work.
