### ISSUE TITLE
Reporter blocks in flyout are glowing when the checkbox is checked

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1216]
### Expected Behavior

Reporters shouldn't glow.

### Actual Behavior

Reporter glows in flyout
![image](https://user-images.githubusercontent.com/2855464/34746854-c0ae689a-f563-11e7-984e-a1672c4e2292.png)

### Steps to Reproduce

Check box next to "current ()" reporter

### Operating System and Browser

Windows 10 Chrome

**Comment by hedgehog125** [comment]
I get the same issue too in Chrome 63.0.3239.132 on Mac OS X 10.11.6.

**Comment by GabriellaKwan** [comment]
Same issue with Chrome  63.0.3239.132 on Windows 10. All the reporters with checkbox in the front don't glow except for "current[year]" and "[property] of [stage/sprite]".
![image](https://user-images.githubusercontent.com/34883965/34866869-0679a72a-f7b9-11e7-99c3-28f37b7a9781.png)

**Comment by amazinigmech2418** [comment]
It seems like it "thinks" you are clicking it when selecting the checkbox.

**Comment by dgnball** [comment]
Ok, so I dug into this using the FF debugger. Where this gets set is in scratch-vm/src/engine/execute.js (https://github.com/LLK/scratch-vm/blob/9d5bbdbf3a00da3978ce62a548e2422989585ad7/src/engine/execute.js#L169). Here is the code snippet (redacted):
```javascript
    const opcode = blockContainer.getOpcode(block);
    const blockFunction = runtime.getOpcodeFunction(opcode);

    if (typeof blockFunction === 'undefined') {
        thread.requestScriptGlowInFrame = true;
```
So, when the "current" block is selected, this section of code in the scratch-vm gets polled continuosly until it is unselected. `opcode` gets set alternatively to `sensing_current` and `sensing_currentmenu`. When `opcode` gets set to `sensing_currentmenu`, `blockFunction` becomes `undefined` and it is this which causing the block to "glow".

At this point my understanding of the code base has hit a brickwall. I'm not sure if the bug is that `getOpcodeFunction` is returning `undefined`, that `opcode` gets set to `sensing_currentmenu` or that maybe everything is working fine but just isn't producing a consistent user experience.

**Comment by amazinigmech2418** [comment]
@dgnball It probably is the undefined thing. It seems like maybe when checked, the block function is set to undefined.

**Comment by paulkaplan** [comment]
Seems to have been fixed
