### ISSUE TITLE
Phase 2 - Library design and filter system

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1254]
![image](https://user-images.githubusercontent.com/31634240/34963510-f0bcc6e6-fa16-11e7-8922-276fbbbdf016.png)
I think it would be helpful to be able to sort libraries.

**Costume options:**
- People
- Animals
- Objects
- Letters
- Food
- Music
- Flying
- Space
- Walking

**Backdrop options:**
- Indoors
- Outdoors
- Patterns
- Space
- Music
- Holiday

**Sound options:**
- Human
- Percussion
- Instrument
- Sound Effects
- Computer
- Animal
- Dance

**Extension options:**
- Hardware
- Software
- Sound
- LEGO

**Comment by thisandagain** [comment]
We are working on some tagging schemes and other ideas for the libraries. I'll close this in favor of #355

**Comment by carljbowman** [comment]
## Libraries Phase 2 - Tags/Filters

### Overview
Currently we only have the ability to keyword search our libraries. This search only based on the name of the media, e.g. Searching the sprite "dog" will only return "dog1" and "dog2" as results. 

**Tags**: We would like to add a way to tag media (Sprites, Costumes, Backdrops, Sounds, Extensions). Typically these tags will be relatively fine grained, so that when searching things like "puppy", search will also return "dog1", "dog2", etc. At first this will be a manual process of adding tags to media.

**Filters**: We would like to use the same tagging system for higher-level groupings. These groupings will be exposed as toggle-able UI filters. For example, having the a "Animals" tag  to put on "dog1", "cat1", "octopus", etc.

At first applying Search and Filter(s) will be limited to one at a time. See sketches below (specifically Step 4) for more info. 

#### Sprite / Costume Filters
- Animals
- People 
- Fantasy
- Dance
- Music
- Sports
- Food
- Fashion

#### Backdrops Filters
- Fantasy
- Music
- Sports
- Outdoors
- Indoors
- Space
- Underwater
- Patterns

#### Sounds Filters
- Loops
- TBD - @ericrosenbaum - Would you mind suggesting ~6-8 high-level filters?

#### Extensions Tags
Since the Extension Library is not as extensive as other libraries, exposing tags as filters feels a bit like overkill. That said, it we should begin to tag Extensions. One thought would be to tag things with requirements, e.g. "Bluetooth", "Internet Connection", etc.

### Sketches
These sketches only show the Sprite Library, but the same system should be applied to the Costume, Backdrop, and Sound Libraries.

Here is an InVision prototype to click through: https://invis.io/7HGK8NA6SMX

#### 1) Add Sprite
![add sprite via library](https://user-images.githubusercontent.com/3409578/37989797-68fd7784-31d2-11e8-9c54-93803943415e.png)

#### 2) Toggling on "Animals" Filter
For now, filters can only be applied one at a time. 
![click filter on animals](https://user-images.githubusercontent.com/3409578/37989816-71b3301c-31d2-11e8-91f1-a91281282032.png)

#### 3) Filtered Results for "Animals"
![filtered2](https://user-images.githubusercontent.com/3409578/37990088-4adc9f68-31d3-11e8-8189-f066f32e109f.png)

#### 4) Clicking into Search
For now, Searching and Filtering will act exclusively. For example, one cannot apply the "Animals" and then search the filtered sprites for "Puppy", instead searching for "Puppy" will clear the active filter and act as it's own filter on all the sprites. 

To prevent a jarring jump to when clearing a filter, the filter should remain on "Animals" until the first keystroke in search bar. 
![filtered](https://user-images.githubusercontent.com/3409578/37989875-9dcd178a-31d2-11e8-9081-08e17c86b8f4.png)

#### 5) Searching for "puppy"
The search bar should grow horizontally upon focus, but toggle off the "Animals" filter until the first keystroke. 
![searching](https://user-images.githubusercontent.com/3409578/37989896-ab19526e-31d2-11e8-9b1d-b62b0a334e73.png)

#### 6) Clicking to Add "Dot"
![add dot](https://user-images.githubusercontent.com/3409578/37989905-b77fdaa0-31d2-11e8-8e34-87b9d10e9b5b.png)

#### 7) Dot Added to Project
![dot added](https://user-images.githubusercontent.com/3409578/37989917-bdf94a92-31d2-11e8-93f5-a50625f42336.png)

**Comment by ericrosenbaum** [comment]
Here are some sound filters:

- Animal
- Effects
- Human
- Loops
- Notes
- Percussion
- Space
- Sports
- Voice
- Wacky
