### ISSUE TITLE
Sprite, Costume, Sounds, Backdrop Tile Refresh

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1332]
We currently do not have costume and sound numbers in the editors which can make creating projects difficult that specify a specific costume or sound via blocks.

**Comment by Tau5** [comment]
Yep

**Comment by carljbowman** [comment]
## Overview
This issue was raised due to the lack of Costume / Sounds numbers, but the associated metadata (e.g. Costume size) is also currently missing in 3.0. This is also an opportunity to update the tile the selected tile style to be more prominent. 

**High-level Progress**
- [x] PR Landed for including the costume number
- [ ] Add Meta data
- [ ] Update selected state

## Sprite Tiles
![code tab](https://user-images.githubusercontent.com/3409578/38270531-ab454e9e-3751-11e8-9cfc-e9282e381528.png)

**Interaction States**
<img width="400px" src="https://user-images.githubusercontent.com/3409578/38271391-5c4ee9e6-3754-11e8-9f25-7f993ed6f833.png"/>

## Costume Tiles
Info Displayed
- Costume Order Number
- Artwork Dimensions 

![costumes tab](https://user-images.githubusercontent.com/3409578/38271681-1221c4aa-3755-11e8-8c46-713388471b46.png)

**Interaction States**
<img width="400px" src="https://user-images.githubusercontent.com/3409578/38271707-2b5f6724-3755-11e8-85d0-ffe8aa16cf3b.png"/>

## Backdrop Tiles
Info Displayed
- Costume Order Number
- Artwork Dimensions 

![backdrop tab](https://user-images.githubusercontent.com/3409578/38274411-bb137b38-375c-11e8-8e51-ca7b66d91591.png)

**Interaction States**
<img width="400px" src="https://user-images.githubusercontent.com/3409578/38274417-bf13213e-375c-11e8-992a-1ac9a822dd10.png"/>

## Sound Tiles
Info Displayed
- Costume Order Number
- Sound Duration

![sounds tab](https://user-images.githubusercontent.com/3409578/38271778-5c3c9fb0-3755-11e8-8583-8fb44912c8ed.png)

**Interaction States**
<img width="400px" src="https://user-images.githubusercontent.com/3409578/38271806-70c2f862-3755-11e8-9330-dc76c44f8a10.png"/>

**Comment by carljbowman** [comment]
Assigning @thisandagain for triage

**Comment by mrjacobbloom** [comment]
Is it even possible to upload sounds longer than an hour? It might make more sense for it to be `00:00.00` or just `123 sec`

**Comment by carljbowman** [comment]
@mrjacobbloom - Good call. Updated.

**Comment by paulkaplan** [comment]
Need a bit more information to get this implemented:
- Is the outline color and the "x" background color the same transparent color? If so, is it motion primary with 20% transparent? (that is what we are using right now for the outline)
- Could you post the sound asset? Currently there is a different, less round one.

**Comment by carljbowman** [comment]
> Is the outline color and the "x" background color the same transparent color? If so, is it motion primary with 20% transparent? (that is what we are using right now for the outline)

Sorry about that. Good catch. My files are out of sync with github, updated sketches above. The delete "x" should not have a transparent background. 

> Could you post the sound asset? Currently there is a different, less round one.

Sure thing. Here you go: [sound.svg.zip](https://github.com/LLK/scratch-gui/files/1884335/sound.svg.zip)
