### ISSUE TITLE
Green flag/stop button

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-gui#15]
Copying this as it's a line item from the prototype plan. I'm assuming it just means getting the styling right.

**Comment by CosmicWebServices** [comment]
Yeah I always want a glow or something when I click it but when I do I am sad because it does not glow or change state.

**Comment by LFP6** [comment]
Would it be possible to make this reflect "design-time" vs "play-time" (or at least make it an option that users are able to choose)? The flag/stop really confused me when I started working with Scratch.

The first thing that confused me is that on clicking stop, the scripts stop, but nothing is reset. The second point of confusion is that even when "can drag in player" is set to off, I can still drag a sprite after hitting the green flag while in the designer.

I can understand that both of these (particularly the first) are implemented for the sake of transparency for newer users, but if there could be a way to make this function as a true design/play (or play/stop playing) indicator, I would personally find working in the editor a lot less awkward.

**Comment by rschamp** [comment]
Glows are in, but we need to refine the design for the states. @carljbowman When you have a chance could you throw in a comp for "playing" vs "stopped" states w/r/t the flag/stop buttons?

**Comment by carljbowman** [comment]
@rschamp - We should keep the UI pretty simple for the prototype and focus on functionality. Then we can do a more holistic pass of visual hierarchy once things in the GUI are further along. 

Scratch 2.0's Green Flag and Stop states: 
**Inactive ('Stopped') — Greenflag** 
<img width="101" alt="screen shot 2016-12-12 at 1 49 52 pm" src="https://cloud.githubusercontent.com/assets/3409578/21112069/4581988a-c072-11e6-9fe0-4eb6d1d43585.png">

**Active ('Playing') — Greenflag**
<img width="105" alt="screen shot 2016-12-12 at 1 55 27 pm" src="https://cloud.githubusercontent.com/assets/3409578/21112156/ab8aca8e-c072-11e6-899c-e3548259d409.png">

**Hover — Greenflag**
Only appears on the Inactive 'Stopped' state
![screen-shot-2016-12-12-at-1 56 47-pm](https://cloud.githubusercontent.com/assets/3409578/21112247/12d97c4e-c073-11e6-9aff-a64e1c640528.png)

This behavior seems fine for now. Rather than that using the CSS saturation filter like you showed me, let's alter the opacity based on state.

Animate Your Name 3.0 Prototype Green Flag and Stop states:
**Inactive ('Stopped') — Greenflag — Opacity=50%** 
<img width="238" alt="screen shot 2016-12-12 at 3 28 35 pm" src="https://cloud.githubusercontent.com/assets/3409578/21115525/b429d20e-c07f-11e6-841e-7c7c414b1ad0.png">

**Active ('Playing') — Greenflag — Opacity=100%**
<img width="264" alt="screen shot 2016-12-12 at 3 29 35 pm" src="https://cloud.githubusercontent.com/assets/3409578/21115626/23da6ece-c080-11e6-80ee-48b5c0f1df39.png">

**Hover — Greenflag — Opacity=100% + Mouse=Pointer**
<img width="306" alt="screen shot 2016-12-12 at 3 32 46 pm" src="https://cloud.githubusercontent.com/assets/3409578/21115652/493ec9a8-c080-11e6-9336-50a7a6ee814a.png">

As far as sizing goes. While sketching I have generally kept icons at 16px by 16px. That said I could see future explorations where we would need to adjust the size for Greenflag and Stop to draw more prominence.

**Comment by LFP6** [comment]
That seems backward to me. It looks like the flag is disabled/"depressed", and that I can't click that, but instead the influence is on the stop sign, which I am led to click. Same in the reverse.

**Comment by rschamp** [comment]
In my experience there is no toggle state that looks correct for everyone the first time — it's kind of a white and gold/black and blue dress situation :)

**Comment by LFP6** [comment]
Could continue with the idea of skinning from scratch-blocks if it winds up annoying me, I suppose!

Side note, are things like this done with classes, or inline-styles?

**Comment by carljbowman** [comment]
@LFP6 - Totally a valid point. It's awesome that folks care so much about these details and give feedback. We are very early in prototyping the GUI. Our current focus us on the general layout, functionality, and connecting some of that larger parts of the editor.

This iteration is less focused on the visual hierarchy of the UI, but gives enough for us to continue to play with the overall layout and tease out some ideas. As I mentioned in my earlier post we will continue to refine the interface more holistically and in detail like we did with the blocks. Introducing all that detail could add a lot of addtional complexity to prototyping. 

The concept sketches may have set a precedent for a level of polish that is further out. Those sketches just scratch (pun totally intended) the surface of types of visual hierarchies. I am very excited to continue to explore these details more, but there is quite a bit of work todo before hand.
