### ISSUE TITLE
Pen Eraser Feature

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1519]
### Feature
Pen should have eraser that erases something. So far there is only one way to erase - "Clear" block, but it erases everything.

Related Blocks:
*"eraser up"
*"eraser down"
*"set eraser width to ()"
*"change eraser width by ()"

### Actual Behavior
This does not exist

### Operating System and Browser
Firefox 58.0.2
Windows 7 Home Premium 64bit SP1

**Comment by hedgehog125** [comment]
Maybe something to clear rectangles too would be useful?

**Comment by Kenny2github** [comment]
@hedgehog125 maybe something to *fill* rectangles would also be useful? :stuck_out_tongue:

**Comment by hedgehog125** [comment]
@Kenny2github do you mean to draw them filled?

**Comment by Kenny2github** [comment]
@hedgehog125 no, I meant it would be strange to have a tool to clear rectangles but not fill them with color :)

**Comment by hedgehog125** [comment]
@Kenny2github oh, ok.

**Comment by hedgehog125** [comment]
Maybe there could be an advanced pen extension and this suggestion could be in it? Similar to my suggestion I wrote a while back: https://scratch.mit.edu/discuss/topic/288708/

**Comment by Kenny2github** [comment]
@hedgehog125 since the pen blocks are an extension, that allows for more advanced stuff to be put in it - so this would be a nice idea for it :)

**Comment by hedgehog125** [comment]
@Kenny2github yes, however the pen starts off fairly simple: you could just put the pen down and draw a line wherever the character goes. But if the more advanced pen blocks were in the main extension then it might cause confusion partly due to the amount of different pen blocks, but also due to their complexity e.g the capture block I suggested would use lists and lists are pretty high-end so that would be confusing.

**Comment by apple502j** [comment]
Moved to  #5406
