### ISSUE TITLE
Say blocks appear further a part so the conversation between sprites looks weird

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1591]
### Expected Behavior

Say blocks for each sprite should appear closer to one another
https://scratch.mit.edu/projects/56987002/#editor

### Actual Behavior
Say blocks appear further a part so the conversation between sprites looks weird
![say_blocks_far_apart](https://user-images.githubusercontent.com/3812168/37161487-d11e92a6-22c0-11e8-9712-a6db37b04e60.png)

### Steps to Reproduce

1. Create a project between two sprites that talk in 3.0
2. Compare that project to something similar in 2.0
3. Notice that the say blocks in 3.0 are much further a part.
4. Note: Importing an existing 2.0 project into 3.0 does not show the issue. Only using new sprites in 3.0 shows the issue.

### Operating System and Browser

Chrome 64

**Comment by techwonder21** [comment]
Using 3.0 sprites in 2.0 works correctly.
https://scratch.mit.edu/projects/208667184/

**Comment by techwonder21** [comment]
If the say block fix is extensive, is it possible to just fix it for dinosaur1 and duck sprite initially?

**Comment by hedgehog125** [comment]
I've also noticed another bug (see the gif).
![scratch3 say bug](https://user-images.githubusercontent.com/16543008/37209456-4dabdd56-239d-11e8-9b16-99056ccda1f8.gif)

**Comment by thisandagain** [comment]
@cwillisf @paulkaplan Any thoughts on the easiest path to tightening up the offset on these? This is causing some trouble for some of the resource developers.

/cc @carljbowman

**Comment by paulkaplan** [comment]
@BryceLTaylor yeah same issue.

Did some digging into how Scratch 2 works ([src](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/scratch/ScratchSprite.as#L631-L648)): it uses the bounding box of a thin strip at the top of the sprite, instead of the bounding box of the entire sprite. 

I propose we introduce a new method on the drawable & renderer that retrieves this bounding box. We can do that by taking an AABB of only the convex hull points that are in this region.

Then the VM can use this new method (`renderer.getBoundsForBubble(drawableID)`, e.g.) instead of using `renderer.getBounds()` when positioning the bubbles: https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_looks.js#L122

@cwillisf seem like a good way to do it? I know filtering the convex hull points isn't technically a geometrically sound operation, it would be better to either redo the convex hull calculation in the strip or take an intersection with the overall convex hull with the strip, but because the strip is so small, I doubt it could really get into too much trouble...

**Comment by thisandagain** [comment]
Thanks for the investigation @paulkaplan. This approach seems reasonable. 👍
