### ISSUE TITLE
Backdrops under Costume tab does not show the same image on the stage

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1599]
### Expected Behavior

Backdrops under the Costume tab should reflect the same image on the stage. This may be both a 2.0 and 3.0 issue
<img width="1630" alt="scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/37209132-0d6a64c2-2372-11e8-8b36-ffde393a118e.png">
https://preview.scratch.mit.edu/#73399968
https://scratch.mit.edu/projects/72180668/#editor

### Actual Behavior

Backdrops under Costume tab does not show the same image on the stage

### Steps to Reproduce
Open 2.0 project in 3.0
Click on backdrops and Costume tab
Click through each backdrop and notice differences

### Operating System and Browser

Chrome 64

**Comment by Clark-E** [comment]
I think that what you’re witnessing is the “obstacle” sprite blending in with the background. The background is displaying properly.

**Comment by Clark-E** [comment]
Also, problems related to rendering most likely belong in the scratch-render repository.

**Comment by Clark-E** [comment]
And, whenever you’re testing stuff, you should use [https://llk.github.io/scratch-gui/develop](url).

**Comment by fsih** [comment]
I agree with @Clark-E that it looks like you're seeing the obstacle sprite?

However, I'm seeing an issue where the backdrop does not take up the full width of the stage. It seems like that issue is new since this bug was filed?
![image](https://user-images.githubusercontent.com/2855464/37302802-f31f73d0-2602-11e8-8b89-613ce72833b3.png)

**Comment by fsih** [comment]
I will file that as a different bug
