### ISSUE TITLE
Can't make pull request for this repo

### ISSUE THREAD

**Issue by Clark-E** [LLK/scratch-gui#1662]
### Expected Behavior

_Please describe what should happen_

When working on GitHub, you should be able to make pull requests.

### Actual Behavior

_Describe what actually happens_

The "make pull request" button is disabled.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

In order to reproduce this, I'd have to give you access to my account.

Actually, I'm 99% sure that it's not letting me pull because I haven't made an issue on here. Once I make this issue, I should be able to make a pull request. (Edit, I still can't)

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

xfce4, firefox

**Comment by Clark-E** [comment]
Actually, no. It's still not letting me, despite getting a pull request accepted (and merged) on scratch-blocks. Do I need to get approved by an owner or something?

I'm trying to fix issue #1260, by the way.

**Comment by rschamp** [comment]
As far as I know, there's no way to disable or restrict pull requests for public repositories.  What do you see if you visit https://github.com/LLK/scratch-gui/pull/new?

**Comment by Clark-E** [comment]
This is what I get:

![screenshot 2018-03-26 at 10 59 46 am](https://user-images.githubusercontent.com/35299276/37914303-ef739a58-30e4-11e8-9961-f596ca3eb84a.png)

The button is grayed out, and there's no way to click on it.

I just had another thought, though: Maybe Github thinks my repository is out of date? I keep my local git repository up to date, but online, it says it's 49 commits behind. I'll try and see if I updating it works.

**Comment by rschamp** [comment]
@Clark-E Github expects you to be making a pull request after you've already made a new branch on your fork, made and tested all your changes, and then pushed your commits to your branch.  After you've done that, you can choose your branch with changes from the dropdown on the right.  It's not letting you make a PR from Clark-E:develop to LLK:develop since there is nothing to pull.

You should make a new branch from LLK/scratch-gui's develop branch called e.g., `fix-1260`, then make all your changes and test them locally. Then commit them and push up your branch to your fork.  After you do that Github will allow you to choose your `fix-1260` branch in the dropdown on the right side of the "make a new PR" interface.

**Comment by Clark-E** [comment]
Ok, I’ll try this

**Comment by Clark-E** [comment]
This worked, and the pr was made. Thanks for the help!
