### ISSUE TITLE
File->Download causes crash on iOS Safari

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1783]
### Expected Behavior

Selecting File->Download to your computer on iOS Safari should work, or be grayed out.

### Actual Behavior

It tries to load a URL starting with `blob`, and shows an error page including `WebKitBlobResource error 1` 

### Operating System and Browser

iOS 11.2.2 Safari

**Comment by hedgehog125** [comment]
Maybe it could detect you're on ios and tell the user that the device can't download files? Otherwise it may be confusing for younger users?

**Comment by tyreun** [comment]
Same issue with iOS11.3

**Comment by paulkaplan** [comment]
Looks like using a library that handles the many edge cases of saving files out of the browser like https://github.com/eligrey/FileSaver.js/ would help. It is definitely possible to save those files on mobile safari, just takes a fair bit of trickery.

**Comment by BryceLTaylor** [comment]
https://github.com/LLK/scratch-gui/issues/1030 contained some screenshots that are out of date but might be useful.  These two were duplicates.

**Comment by exomut** [comment]
I took a look around in the “src/containers/project-saver.jsx” file since it seems to be the code causing the problem. I wasn’t able to solve the issue, but if you surround lines 48 and 49 with a setTimeout() you are able to get a downloadable version of your project on iOS.

```javascript
setTimeout(function(){
    window.URL.revokeObjectURL(url);
    document.body.removeChild(saveLink);
}, 1000);
```

The only problem is that the filename can’t be set. It will save as “Unknown.zip”. Using a file manager on iOS you can rename the file to “Your Project.sb3” and upload it back to Scratch 3.0 without error. (Tested on iOS 12)

Running the Scratch site in full screen while canceling a save still crashes Safari though.

I am now able to work on Scratch projects on my iPad and save them. Although, renaming is a hassle. FIlesaver.js looks like it could be an option since it is using the MIT license, but I am not too sure how compatible the MIT and BSD licenses are.

**Comment by rickwookie** [comment]
Disappointing to see no progress on a fix for this a year on, particularly now that iOS/iPadOS 13 fully supports file downloads within mobile Safari.

**Comment by tyreun** [comment]
Hi,

Take a look at 

http://www.ac-grenoble.fr/maths/scratch/

Cheers

Ronan

**Comment by tyreun** [comment]
You can download on iOS with safari

**Comment by benjiwheeler** [comment]
Sorry, I'm responsible for this not getting more attention because I assigned it to myself thinking I would have time to work on it, so that made it seem like someone was working on it.

I'm hoping we'll have some time soon to take a look at this. We are open to community suggestions around what to do. Sounds like @exomut's approach would at least be an improvement to the way things are now, even if it wouldn't make the experience quite what we want it to be.

**Comment by dullbananas** [comment]
I want this fixed. Same issue happening in iPadOS 13.4

**Comment by benjiwheeler** [comment]
Partially addressed by https://github.com/LLK/scratch-gui/pull/5101 , but still needs urgent attention

**Comment by ericrosenbaum** [comment]
@tyreun I'm investigating our options. it looks like your site has a solution that allows saving and loading files on iOS 13, with correct filenames (though they have .zip at the end). Can you share a code snippet? Thanks!

**Comment by tyreun** [comment]
Hi,

You can download the source code with the red button

 

Cheers

Ronan

**Comment by ericrosenbaum** [comment]
@tyreun thanks- I did try that yesterday. the download contains the minified version of the source, so I wasn't easily able to find your change (since I don't know exactly what you changed). I also looked at your github fork of scratch-gui and did not find anything relevant there.

**Comment by tyreun** [comment]
Sorry but I’m not the developer, juste a user !

**Comment by ericrosenbaum** [comment]
Oh I understand- sorry about that @tyreun !

**Comment by ericrosenbaum** [comment]
okay, it appears that the solution from @exomut, using a timeout before removing the link, works on iOS 13, and the filename is set correctly (we now have a separate code path for iOS 12 which can stay as is- it's not ideal but prevents the crash there at least). 

The other issue that @exomut mentioned involves running safari in full screen mode (i.e. browser full screen, not scratch full screen), and I was not able to figure out how to use that feature (either it's changed or removed since iOS 12, or something that can only be set by web page headers?).

**Comment by redstone-scratch** [comment]
Interesting, I'll test this, even though I'm probably not helping. What version of iOS and Safari?
