### ISSUE TITLE
Sprite thinks it's touching mouse pointer outside project pane

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#179]
### Expected Behavior

I don't expect the sprite and mouse to touch unless the mouse is in the project pane.

### Actual Behavior

The mouse pointer is located near the lower left corner of the project pane, in the editor scripting area. If the sprite goes off the edge of the project pane, sometimes it seems to still think it's touching the mouse pointer?

![out](https://cloud.githubusercontent.com/assets/1320456/23567275/8a7980c4-0023-11e7-942c-a532517be4b8.gif)

### Steps to Reproduce

- Create a script like the one below
- Press play
- Move the mouse pointer somewhere in the scripting area
- Wait for the project to clear itsef

<img width="288" alt="screen shot 2017-03-03 at 3 02 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/23567045/7ca893c8-0022-11e7-9e56-640504791518.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by jwzimmer** [comment]
@ericrosenbaum & I saw this issue again today when trying out the speech & WeDo extensions. (Just noting it does still happen.)

**Comment by Kenny2github** [comment]
Reproduced:
![gui](https://user-images.githubusercontent.com/28599280/27025307-9f27c11c-4f8c-11e7-95d3-584b831fbe27.gif)
Anybody know what that sweet spot where it starts dancing is about?

**Comment by paulkaplan** [comment]
@thisandagain @rschamp @tmickel (basically anyone who might know), does anyone have any idea why the mouse io data was originally written to clamp to the stage bounds? That is the root cause of this problem: when you move your mouse around, it's position is clamped within the [-240, -180, 240, 280] box, so it can trigger the "touching mouse pointer" for a sprite on the edge even if your mouse is horizontally all the way across the screen... I can't think of any reason to keep this, but it was designed specifically for that behavior, so there must be some reason?

**Comment by tmickel** [comment]
I believe blocks (like (mouse x) (mouse y) reporters, go to mouse pointer, point towards mouse pointer) use a clamped value in 2.0. "Touching mouse pointer" seems like an exception here? Not sure exactly which blocks are clamping, but probably makes sense to not-clamp by default and clamp in the relevant block... :)
