### ISSUE TITLE
Speech bubble glitch

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1817]
### Expected Behavior
Speech bubble conversation should occur without any glitches
https://scratch.mit.edu/projects/56987002/#editor

### Actual Behavior
Speech bubble glitch happens when one of the two things happens:
2 sprites are talking back and forth
1 sprite has multiple "say" blocks
https://preview.scratch.mit.edu/#56987002

### Steps to Reproduce
1. Create a project in 3.0 or load in a 2.0 project that has multiple "say" blocks
2. Click the green flag
3. Observe the speech bubble glitch

### Operating System and Browser
Chrome 65

**Comment by paulkaplan** [comment]
Ok, tracked this down to https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_looks.js#L169-L179

I think the issue is that the visibility is being toggled synchronously, but `updateTextSkin` looks like an async operation. Might have to return a promise from that and toggle visibility once it is ready.
