### ISSUE TITLE
Sprite Info fields' focus competes with blocks call keyboard inputs

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#182]
We will need to discuss this more. Scratch 2.0 has similar issues when naming a Sprite.

Repo:
1. Drag a block that listens for keyboard inputs (e.g. when space key press)
2. Click into a field in the Sprite Info area (e.g. x) 
3. Begin typing and retain focus -- when space key pressed block does not execute

**Comment by jwzimmer** [comment]
A comment from the internal playtest, 3/3/17:
> after I select a rotation style, the dropdown menu keeps the focus, so if I press space bar (to control the project) it opens it up again, instead of executing my script

I noticed a similar thing in https://github.com/LLK/scratch-gui/issues/169.

**Comment by jwzimmer** [comment]
Note: this also happens with e.g. the block values in "change color effect by x"; if you leave your cursor in the field, then clicking space won't activate the script. This is a little unexpected on the one hand, especially since you can drag a block into a stack have it continue playing... it feels like you can actively be editing a script and execute it. However, on the other hand it makes complete sense, because if you were using e.g. a "say x" block, you wouldn't always be trying to activate the script when you hit the space key (if you were typing a sentence like "Hello, nice to see you!" etc.).
<img width="245" alt="screen shot 2017-03-13 at 10 56 36 am" src="https://cloud.githubusercontent.com/assets/1320456/23859947/c1dd63fe-07db-11e7-859d-5c2a830b46c7.png">

**Comment by Airhogs777** [comment]
So would the solution be to detect non-numbers when editing number inputs?
