### ISSUE TITLE
Stamp / pen not always drawing

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#191]
Reported during internal playtest 3/3/17.

### Actual Behavior

When loading a project, sometimes stamp / pen down do not draw - reloading the page helps

### Operating System and Browser

_Mac & Chrome_

**Comment by morantsur** [comment]
I found a reproducible example in microworlds, but not sure if it has the same root cause. 

When using https://morantsur.github.io/scratch-gui/#art, loading a project right away works well - the sprite stamps. But, if you click the green flag and stop, and then load a project, it doesn't stamp. 

(You can save the starter project and load it to see it reproduce)

**Comment by thisandagain** [comment]
Thanks @morantsur !

**Comment by paulkaplan** [comment]
Since pen is now manually loaded, and auto-loading with a project seems to work correctly, I'm going to close this.
