### ISSUE TITLE
Error: The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page.

### ISSUE THREAD

**Issue by LukeSchlangen** [LLK/scratch-gui#2017]
### Expected Behavior

No warnings in console for production build

### Actual Behavior

Seeing over 2000 identical warnings that say:

`The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu`

<img width="1280" alt="screen shot 2018-05-09 at 7 32 35 pm" src="https://user-images.githubusercontent.com/5384581/39846252-3f7a451c-53c0-11e8-9ae1-4ead3516cafe.png">

### In Development

1. `npm install`
2. `npm start`

#### In Production

1. `npm install`
2. `npm run build`
3. Serve static files with `serve -s build`
4. Navigate to `http://localhost:5000` and open console

### Operating System and Browser

Mac OS 10.13.4 Chrome 66.0.3359.139

**Comment by BryceLTaylor** [comment]
I am unable to reproduce this on mac 10.13.5 using chrome v. 67.0.3396.87

**Comment by JinXJinX** [comment]
Because this problem is actually exists. And I can reproduce this problem on current online version scratch.

So please consider reopen this issue. @BryceLTaylor @thisandagain 

## Steps to Reproduce

1. open Chrome
2. Go to https://scratch.mit.edu/projects/editor
3. open developer tool
4. open console
4. refresh page and **do not click page**
5. you will see the warnings

## Operating System and Browser

Mac OS 10.14.2 Chrome 71
Chrome OS 71

**Comment by UntilGone** [comment]
same to me
