### ISSUE TITLE
2.0 project sprite doesn't behave correctly in 3.0, doesn't follow mouse pointer until you click the block stack

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#206]
Reported via internal playtest 3/3/2017.

### Expected Behavior

In 2.0, the whale looks like a whale and follows the mouse pointer while retaining it's shape. In 3.0, the whale is shaped incorrectly, and can't follow the mouse pointer consistently, until you click the relevant block stack with your mouse to activate it.

### Actual Behavior

- The console says `Ignoring non-existent input VARIABLE in block data_variable`, so I don't know if this issue could be caused by the unfinished state of variable/ data implementation in 3.0.
- https://llk.github.io/scratch-gui/#102160644
- Here you can see the sprite shape as it tries to follow the mouse in 3.0:
![out](https://cloud.githubusercontent.com/assets/1320456/23627193/c99359fe-027d-11e7-9bee-a4e0a6bb77b8.gif)
- Here you can  see the incorrect sprite shape in 3.0 before you have pressed k to get it to follow the mouse pointer:
![out](https://cloud.githubusercontent.com/assets/1320456/23626603/788b357e-027b-11e7-80bc-aaa8bc8eec9b.gif)

### Steps to Reproduce

- Green flag in https://llk.github.io/scratch-gui/#102160644
- Press k key
- Move mouse
- In 2.0, the whale follows the mouse pointer after you press k once
- In 3.0, you have to keep pressing k, then the whale will repoint towards the mouse pointer but won't follow it
- In 3.0, you have to click the "when k pressed" stack of blocks with your mouse; then the whale will consistently follow the mouse pointer
- Compare 2.0 & 3.0: https://scratch.mit.edu/projects/102160644/#editor

### Operating System and Browser

_Mac & Chrome_

**Comment by bigeyex** [comment]
Solved in [scratch-vm pr562](https://github.com/LLK/scratch-vm/pull/562)

scratch-vm has a bug that when a clone is deleted, the next thread will be skipped;

This program is a abuses Scratch's thread system^_^:
- A clone of "whale" is created and then deleted in "When I start as clone";
- but Scratch threads will yield upon loops (repeat xxx times);
- since there is a "repeat 43" in "when I start as clone", it will start to delete clones after 43 clones are created, resulting in 43 clones exist in any time of the execution.
- then when the "k" key is pressed, variable "Keyboard" will be flipped [# of clones] times, 43 In this case, which is an odd number, setting the flag and making the whale follow the mouse.

But in Scratch 3.0, since there is a thread-skipping bug, there will be 44 clones - an even number.  So no flag is set and the "k" key does nothing.

**Comment by towerofnix** [comment]
This project seems to be working correctly now.

**Comment by thisandagain** [comment]
👍 Confirmed. This project is now working properly.
