### ISSUE TITLE
Double-right/middle-clicking toggles monitor modes

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2089]
### Expected Behavior

Only double-left-clicking toggles a monitor's mode. (This is the behavior in Scratch 2.0.)

### Actual Behavior

Using the right-mouse or middle-mouse to double click also toggles a monitor's mode.

### Steps to Reproduce

Show a monitor (click a checkbox in the block palette), then double-click it using the right or middle mouse buttons. Note that the monitor mode changes (to "large" or "slider").

### Operating System and Browser

Firefox 61.0b5, Debian (testing).

**Comment by sjhuang26** [comment]
I can't repro this; the behavior seems to be as expected. For me, right click brings up the context menu while middle click does nothing.

(Chrome 66, Windows 7, on development server.)

**Comment by towerofnix** [comment]
Thanks for testing on Chrome and Edge -- I just tested on Chromium and cannot repro there, but still can on Firefox. So it looks like this is specific to Firefox, for whatever reason.

**Comment by sjhuang26** [comment]
It seems like Firefox implements its click listeners differently.

[Stack Overflow](https://stackoverflow.com/questions/43144995/mouse-right-click-on-firefox-triggers-click-event):

"By default, in all browsers right click event is captured by  addEventListener('contextmenu'), otherwise a right click will open a window with some options (each browser has different one).

In Firefox, when you add addEventListener('click') to the document object, it will capture any mouse clicking events (left, right, wheel) on the document and it will disable this right click behavior.

In addition, this is what Mozilla documentation says in Mouse Events section, although the (ANY button) stuff is not activated until you add the listener to the document object

click: A pointing device button (ANY button; soon to be primary button only) has been pressed and released on an element."

**Comment by BryceLTaylor** [comment]
I can not reproduce this on any browser, including Firefox on Window or Mac.  Is it possible Firefox has changed this behavior?

**Comment by apple502j** [comment]
I can't repro either - Firefox 77

**Comment by towerofnix** [comment]
Cannot repro on FF 78, same computer/OS. Gonna close this!
