### ISSUE TITLE
sensing ask escape characters error

### ISSUE THREAD

**Issue by wwj718** [LLK/scratch-gui#2148]
### Expected Behavior

![image](https://user-images.githubusercontent.com/3153878/40524532-90565940-600d-11e8-93a4-d7604ad7475d.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/3153878/40524527-87ed9962-600d-11e8-8b5c-8d1ed0847b7f.png)

and

![image](https://user-images.githubusercontent.com/3153878/40524574-c88f8ee4-600d-11e8-9447-487c96e41357.png)

### Scratch3.0 branch（develop）
https://llk.github.io/scratch-gui/develop/

### Operating System and Browser

Mac OS 10.13.3 Chrome 66.0.3359.181

**Comment by towerofnix** [comment]
I'm pretty sure this is actually an issue with scratch-render, since I noticed a "say" block had the same issue:

![A say block containing "Hello!"nice!" <><>"; a speech bubble containing that, but with the special characters replaced with their HTML escape code equivalents](https://user-images.githubusercontent.com/9948030/40570233-0730536c-605f-11e8-9ec0-1d3ddbaadf6a.png)
