### ISSUE TITLE
Handle re-initializing stage, toolbox and workspace when switching between editor and player

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2231]
### Expected Behavior

When clicking the `see inside` button from the project page, or `see community` button in the editor, the project state should be maintained.

### Actual Behavior

Project data is maintained, but the project is not displayed on the stage, and cannot be restarted. When switching from project page to editor, the first sprite is the selected target, but the toolbox shows the blocks for the stage.

### Steps to Reproduce

View a project in the new project preview, then click `see inside` (only available on Media Lab network)

**Comment by chrisgarrity** [comment]
Note: https://github.com/LLK/scratch-vm/issues/1158 is related.

**Comment by kchadha** [comment]
@chrisgarrity, @cwillisf, and I noticed that we are only running the logic in componentDidMount for the GUI container once (by storing a flag indicating that the GUI is already mounted). This ensures that we do not re-attach an audio engine to our vm instance, etc. however, we are not making a corresponding check in the stage container which is responsible for attaching the renderer. Since switching modes (`see inside` or `see community`) mounts the GUI again, the stage gets mounted again and the renderer gets replaced with a new instance which is missing all the state of the old renderer.

@chrisgarrity, @cwillisf, I hope I've summarized this accurately, please feel free to edit or comment on any inconsistencies.
