### ISSUE TITLE
Drag two blocks to backdrops area, these blocks overlapped.

### ISSUE THREAD

**Issue by hahapang** [LLK/scratch-gui#2318]
### Expected Behavior

Blocks will shows normally.

### Actual Behavior

Blocks is overlapped.

### Steps to Reproduce

1. Click Sprite 1. 
2. Drag two blocks to backdrops area.. 
3. Click Backdrops area. 
<img width="1409" alt="qq20180612-190117 2x" src="https://user-images.githubusercontent.com/26299904/41286920-a936540a-6e73-11e8-90d3-f70ec0843b8c.png">
<img width="934" alt="qq20180612-190149 2x" src="https://user-images.githubusercontent.com/26299904/41286925-ab9aa8d6-6e73-11e8-977b-9ce942df190e.png">

### Operating System and Browser

Mac OS 10.12.6 | Chrome 66.0.3359.181

**Comment by thisandagain** [comment]
@hahapang What browser and operating system are you using?

**Comment by hahapang** [comment]
Chrome 66.0.3359.181
Mac OS 10.12.6

发自我的 iPhone

**Comment by thisandagain** [comment]
I'm able to repro this behavior using "share the love" with the backdrop area.

/cc @paulkaplan @fsih

**Comment by hahapang** [comment]
This issue cannot reproduce, because the stage hided the Motion blocks.

**Comment by paulkaplan** [comment]
I'm going to re-open this because you can still do it with other blocks, and they still overlap.

**Comment by paulkaplan** [comment]
@kchadha i've been thinking about this a bit. it looks like the vm knows very little about positioning apart from the XY position of the "top blocks" of each stack (layout is totally handled from that by blocks). So we don't have too much information to work with when sharing blocks since the other sprites blocks aren't currently laid out. One thing we could do is just make sure to offset in both X and Y from the bottom left most block, e.g. I experimented with this snippet in `handleBlockDragEnd`, just before the blocks are shared to the target:
```
            const topSharedBlock = blocks.filter(block => block.topLevel)[0];
            const spriteBlocks = this.props.vm.runtime.getTargetById(this.props.hoveredTarget.sprite).sprite.blocks;
            const spriteTopBlocks = spriteBlocks.getScripts().map(id => spriteBlocks.getBlock(id);
            const maxX = Math.max(...spriteTopBlocks.map(b => b.x));
            const maxY = Math.max(...spriteTopBlocks.map(b => b.y));
            topSharedBlock.x = maxX + 50;
            topSharedBlock.y = maxY + 75;
```
That will at least make sure that the dropped blocks are not on top of each other
![image](https://user-images.githubusercontent.com/654102/64459164-4538dd00-d0c5-11e9-92df-00e9e2eb02e1.png)
