### ISSUE TITLE
Clicking 'x' on list reporter deletes the row below the current row

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#2361]
### Expected Behavior

Clicking 'x' on list reporter deletes the current row

### Actual Behavior

Clicking 'x' on list reporter deletes the row below the current row (except when the last row)

### Steps to Reproduce

Add a new list with a, b, c, d, etc... Delete a row in the middle using the 'x' in the list reporter. The row below is deleted leaving the intended row behind.

### Operating System and Browser

Scratch Develop, Chrome, Windows 10 PC

**Comment by paulkaplan** [comment]
Oh no!

Technically it isn't deleting the row below, it is deleting the correct row, just not resetting the value of the input to the new value of that index. Here is how you can tell:

![list-remove-issue](https://user-images.githubusercontent.com/654102/41471840-b4e0281a-7082-11e8-86d5-7877826dd4c6.gif)

But effectively the same thing, because it will always submit that value when you unfocus the field. Fix is too force the new index/value: https://github.com/LLK/scratch-gui/pull/2363
