### ISSUE TITLE
___ of ___ block should not have backdrop # or backdrop name options

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2389]
### Expected Behavior

The `___ of ____` sensing block should not have `backdrop #` or `backdrop name` options in the dropdown and match scratch 2.0

### Actual Behavior

It has those extra options
![screen shot 2018-06-18 at 4 45 25 pm](https://user-images.githubusercontent.com/1088291/41562209-f6b536a6-7319-11e8-92e3-8466233b6e10.png)

### Steps to Reproduce

Choose Sensing from the Category Menu
Locate the ___ of ___ block (starts as X position of Stage)
Select the first dropdown on the selected block
Note: it has `backdrop #` and `backdrop name` as options

### Operating System and Browser

Chrome on Mac

**Comment by Alzter** [comment]
Sprites using the _ of _ block should also be able to select themselves so clones can use them.

**Comment by towerofnix** [comment]
Fixed in #3695, I think.

**Comment by picklesrus** [comment]
@towerofnix:  Almost fixed :) 

I have one more PR I want to send out and land before I call it fixed. The first menu still keeps the old value selected when you switch the value in the target menu. E.g. if I have "backdrop #" and I switch the target menu to one of the sprites, "x position" should be selected instead of leaving behind the "backdrop #"
