### ISSUE TITLE
You can drag a comment by its line

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2477]
### Expected Behavior
I wouldn't expect dragging the line to work

### Actual Behavior
The comment moves in an odd way when you drag its line
![image17](https://user-images.githubusercontent.com/1088291/41791110-c20a29d2-7622-11e8-96b3-2fe7df65532b.gif)

### Steps to Reproduce
1. Add a comment to a block
2. Drag it by the line.
It can be hard to click exactly on the line, but here is a way to tell:
![clickline](https://user-images.githubusercontent.com/2855464/41931630-a28e0cb8-794c-11e8-9b16-f83c11f09325.gif)

### Operating System and Browser
Windows Firefox

**Comment by paulkaplan** [comment]
Strangely I can only repro this if there are multiple overlapping comments...

**Comment by eqot** [comment]
There is a root cause in [scratch-blocks](https://github.com/LLK/scratch-blocks) and I have fixed this issue locally.
So, could you move this issue to [scratch-blocks](https://github.com/LLK/scratch-blocks), please? I will send a PR for it.

To repro this issue easily, you can tweak ```stroke-width``` of the SVG line from 1 into 10 or more by using Chrome DevTools.
