### ISSUE TITLE
Stage becomes huge

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2510]
### Expected Behavior
Stage tries to fit in the browser

### Actual Behavior
Stage becomes large when browser becomes narrow
Full-screen mode becomes vast
![hugestage](https://user-images.githubusercontent.com/2855464/42015514-b9468708-7a75-11e8-8daa-443ef1d5d2b8.gif)

### Steps to Reproduce
On develop, narrow the browser window

### Operating System and Browser
Mac Chrome

**Comment by paulkaplan** [comment]
@rschamp this is the issue @carljbowman and I were seeing. There are two issues: first, the width/height passed to the `DOMElementRenderer` used to be turned in to CSS width/height by the `Box` element, but are being set as width/height attributes on the canvas dom element. That is bad because for HiDPI screens it is vital that the width/height attribute be different from the CSS width/height. The second problem is that the other properties, like `flex-shrink` are not being applied correctly to the DOMElementRenderer component
