### ISSUE TITLE
Send language parameters to YouTube

### ISSUE THREAD

**Issue by punnerud** [LLK/scratch-gui#2573]
Hi,

I just translated one of the intro videos for Scratch 3.0 to Norwegian on Amara.org.
I can't see that the text is listed as an option (see images), or preferably auto enabled if the video is not in your default language.

This works great on [Code.org ](https://studio.code.org/s/hero/stage/1/puzzle/1) where the translated texts gets auto enabled based on your chosen language on the site.
Could this be enable on Scratch 3.0 to?

We have a team that is eager to translate Scratch 3.0 into Norwegian (and are translating),
but it is not the same if we can't do it for the videos as well.

I think the main fix is to enable that Amara.org gets access to the videos on the “MIT Scratch Team” Youtube account,
the next fix is to send the right language parameters to YouTube based on the language enabled in Scratch.

How it is now (Scratch 3.0): https://i.imgur.com/cQqkwNc.png
How it is on Code.org, example with translation to 29.languages: https://i.imgur.com/s8DwRBn.png
Amara.org image of translated video: https://i.imgur.com/pErHYlL.png
Amara.org translated video for testing: https://amara.org/en/videos/wVcaIKgfZEOa/nb/2213393/

**Comment by punnerud** [comment]
Seems like there is a global YouTube setting to enable community support:
https://support.google.com/youtube/answer/6052538?hl=en

Both ted.com and code.org are referencing to amara.org for doing the video translations:
https://www.ted.com/participate/translate/get-started
https://code.org/translate/videos

**Comment by chrisgarrity** [comment]
Thank you for your interest in helping to translate Scratch we use [Transifex](https://www.transifex.com/llk/public/) as our platform for translating. The new Scratch 3.0 videos are not currently in Transifex because they are still in development. Consider what you're seeing on youtube as drafts that we are trying out with young people to see how they're received. Until we have final scripts for the videos we are not publishing them to avoid having translators do twice the work.
