### ISSUE TITLE
Block toolbox gets squashed when adding a sprite 

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#270]
To reproduce:

1. Switch to the costume / sound tab (away from scripts).
2. Add a new sprite
3. Switch back to the scripts tab

![screen shot 2017-03-23 at 3 37 17 pm](https://cloud.githubusercontent.com/assets/654102/24266851/a128709e-0fde-11e7-99b8-d666c53fb626.png)

There is a current hack in the gui to trigger window resize when tabs change. I think that the toolbox has to be refreshed as well. See  https://github.com/LLK/scratch-gui/blob/develop/src/components/gui/gui.jsx#L31-L36

**Comment by tmickel** [comment]
oh no!! one suspicion: rendering the blocks requires measuring the length of the texts, here: https://github.com/LLK/scratch-blocks/blob/develop/core/field.js#L436 - which requires that the blocks are visible. generally i think blockly expects that its visibility is controlled by https://github.com/LLK/scratch-blocks/blob/a21919e03b33563bf224ad0f1270847a8847fac3/core/workspace_svg.js#L755 - so that work can be done to rerender blocks/other UI components when appropriate. if a new blockly workspace is created when it's hidden by CSS or something else, maybe the above would happen...possibly you could fix it by calling `workspace.render` or something :)

p.s. the new library stuff is _totally amazing_

**Comment by tmickel** [comment]
(another bug, without `workspace.setVisible` (and thus its hideChaff calls) for example, open a menu in a block and switch tabs - the menu stays open)
