### ISSUE TITLE
Host tutorials using a service besides Youtube, or host them ourselves?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2743]
Using Youtube videos in our in-app tutorials is tricky because many schools block Youtube.

Do we plan to host the videos ourselves or on some other service? 

We may need to nail down a good video player.

**Comment by thisandagain** [comment]
We are considering forking the video player source code developed for one of my other projects and may either use that or work with another 3rd party provider that we are in the process of interviewing / negotiating an agreement with.

**Comment by apple502j** [comment]
Why don't you just use `<video>` tag and host by yourself?

**Comment by towerofnix** [comment]
Right, I'm curious what the reasoning is for using anything but the `<video>` tag. It's certainly long supported by every browser 3.0 targets, and is certain to feel more natural than any custom UI, since browser developers typically make the controls look relatively similar to how the rest of their OS does (see Safari for example).

Going to the trouble of negotiating with a third-party company to *play a video* just does not seem worth it. Presumably/hopefully there's more to the company @thisandagain mentions than purely being a video player provider.

**Comment by benjiwheeler** [comment]
@thisandagain I put this in the November 2018 Milestone because it seems relevant to Hour of Code

**Comment by MasterOfTheTiger** [comment]
If you need to use a third party service for some reason, maybe check out MediaGoblin.
