### ISSUE TITLE
Stamp block on mouse pointer down glitchy 

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2791]
### Expected Behavior
Smoother interaction in 2.0
https://scratch.mit.edu/projects/24452141/#editor

### Actual Behavior
Glitchy interaction in 3.0
https://beta.scratch.mit.edu/#24452141

### Steps to Reproduce
Open 2.0 project in 3.0
Click the green flag
Notice that the 3.0 version is more glitchy

### Operating System and Browser
macOS High Sierra
Chrome 68

**Comment by techwonder21** [comment]
@ChampikaF

**Comment by paulkaplan** [comment]
Could you be more specific about what is glitchy? I tried it in the side-by-side compatibility viewer and couldn't see a difference?

https://llk.github.io/scratch-gui/develop/compatibility-testing.html#24452141

![spray-can](https://user-images.githubusercontent.com/654102/43736298-19e87092-998b-11e8-80ac-377ff6bff58d.gif)

**Comment by techwonder21** [comment]
Sure thing. Note: The CS First team is casting and editing 3.0 videos on the beta website.  Even though the glitch issue is hard to reproduce we think it appears on beta.scratch.mit.edu (rather than https://llk.github.io/scratch-gui/develop/). 

When you click and drag sometimes the spray can picks up and jumps to a new spot rather than spraying a continuous line. In 2.0 and the /develop branch this issue does not appear to happen.
https://beta.scratch.mit.edu/#238644602
![screen shot 2018-08-09 at 10 17 22 am](https://user-images.githubusercontent.com/3812168/43904751-79dd4390-9bbd-11e8-9b93-2b76778c919d.png)

**Comment by thisandagain** [comment]
@BryceLTaylor Can you try to repro this for us? If it is indeed not on `develop` it would be good to get an understanding of why.

/cc @rschamp @kchadha

**Comment by BryceLTaylor** [comment]
This mostly seems to behave the same in 3.0 as it does in 2.0 and the distance between the stamps is mostly based on the speed you move your mouse.

However, if you are in the editor mode, it might be easier to pick up the sprite by clicking and dragging than in 2.0.  You don't see this if you are in the comparison mode, because in player mode you can't drag the sprite.  I think this should be filed in another issue after some more research into it.
