### ISSUE TITLE
Some scaling/positioning issues

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#30]
Green flag/stop seem a little small and offset scratch-blocks
Sprite selector bounding box will sometimes cut off text
Sprite selector is not centered on sprite
No bounding box for stage.

**Comment by rschamp** [comment]
Hey @TheBrokenRail — I am going to close this because the design is still very far from being considered done. I think the issues with it are pretty well-covered by comparing it to the designs in #1. And please also be advised, those designs will very likely change as we work on this. Thanks for your report though!
