### ISSUE TITLE
Deleting costumes and sounds is broken

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#312]
Seems to have been caused by the reporting of costumes/sounds from the VM.

**Comment by paulkaplan** [comment]
Tracked this down to the way that `lodash.defaultsDeep` merges arrays. Here is a simple example:

```
oldState = {costumes: [1, 2, 3]}
newState = {costumes: [1, 2]}

defaultsDeep(newState, oldState) 
//=> {costumes: [1, 2, 3]} 
```
this is wrong in our case, we do not want to merge arrays, we just want the new array. 

@rschamp i see that instead of using arrays in many places we transform into objects keyed by ids, is that to prevent this issue? Should we have a costumes map of {id: costume, ...} instead of an array?

We could also use a modified defaults deep like https://www.npmjs.com/package/defaults-deep-preserve-arrays to preserve arrays.

**Comment by rschamp** [comment]
@paulkaplan No, the reason for transforming to objects keyed by ID is just to be able to access targets without iterating over the list rather than any issue with arrays.  I'd be for using that modified defaults-deep. I'd also be for just not merging if we can avoid it.

If we can avoid transforming to an object, I'd be for that too. I think React may be able to help us there if we just key the components by the target ids.
