### ISSUE TITLE
Dragging blocks causes the blocks pane to change size

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#318]
### Expected Behavior

_Please describe what should happen_
When I drag a block from the toolbox, nothing on the screen should move except for the block.

### Actual Behavior

_Describe what actually happens_
When I drag a block from the toolbox, the right side of the page shifts ~20px to the left, slipping under the blocks pane.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Drag a block from the toolbox.

If you revert #263 the issue goes away, but I'm not sure what exactly introduced it, since that was so long ago.  It seems to be related to the `.injectionDiv` toggling between `overflow: hidden` and `visible` on drags.

![drag](https://cloud.githubusercontent.com/assets/1512021/25254694/dcd3ecc8-25f4-11e7-9a54-c46a52a1170d.gif)

### Operating System and Browser

Chrome 57

**Comment by paulkaplan** [comment]
So this is because we have been using the `injectionDiv` to contain the workspace (to do things like the rounded corner radius and correct borders). The problem with that is on drag, the `injectionDiv` gets set to `overflow: visible` to allow you to drag blocks outside the workspace (to anywhere on the page...) That functionality is intentional (see note in code https://github.com/LLK/scratch-blocks/blob/develop/core/block_drag_surface.js#L112-L117). If we want to maintain that functionality, we need to change the way we are styling the injectionDiv, because we can no longer use it as a clipping container. 

Oh the jumping itself is caused by the `overflow:visible` causing a 1px increase in height causing the vertical scrollbar to appear.

**Comment by paulkaplan** [comment]
One way to easily fix this is to just set `overfloy-y: hidden` on the body of the page. Since this is a sigle page app that never scrolls vertically, this probably would be fine. cc @lifeinchords ?

**Comment by rschamp** [comment]
The only issue I see with that is that we would eventually want page scrolling similar to on 2.0, where you are alway able to scroll to the first row of sprites, even if your window is very short.

The long term fix sounds like reverting #263 and do the real fix for that in scratch-blocks?
