### ISSUE TITLE
Adopting TypeScript

### ISSUE THREAD

**Issue by ianobermiller** [LLK/scratch-gui#3186]
Have you considered adopting TypeScript (or Flow) to make development faster and safer? If you'd be open to it, I wouldn't mind taking a crack at getting it setup and beginning to convert the codebase. I know I'd have more confidence as a contributor with the type system backing me up.

**Comment by rschamp** [comment]
We have considered something like it to replace prop types. However it would be a large undertaking since we would want to roll it out across all of our repositories which use Javascript, which are numerous. Rolling out a new style of working in one repo without applying it to the rest can hinder productivity since it increases the complexity of the entire project when you have to switch contexts even more when working on different areas of the code.

We also have not had many ergonomic issues with not using types yet, so the effort required to switch to a typed system currently outweighs the benefit.

**Comment by ianobermiller** [comment]
> Out of curiosity's sake, how would a type system help you, particularly in an app where the majority of the code deals with React?

TypeScript (and Flow) have great support for React, and it allows you to catch many potential and actual bugs without even running the particular code path, like not passing required props, passing more props than you need, or not passing precisely the correct type. It is far easier to type React component props than use propTypes, and you can make types much more specific and thus safer (specifying the actual fields instead of using [`PropTypes.object`](https://github.com/LLK/scratch-gui/search?q=PropTypes.object&unscoped_q=PropTypes.object), for example).

> You'll notice the (vast) majority of functions and classes have JSDocs

JSDoc is definitely better than nothing, but the major downsides are that a) they easily become out of sync with code and b) you do all the work of writing types with almost none of the benefits. Refactoring without types is tedious and dangerous -- basically rely on careful code inspection and automated and manual tests to make sure you aren't breaking anything. With types, changing the name of a prop, for example, is as easy as changing the code and fixing the resulting errors. TypeScript especially has great code completion, go to definition, and even automated refactoring tools.

> Rolling out a new style of working in one repo without applying it to the rest can hinder productivity since it increases the complexity of the entire project when you have to switch contexts even more when working on different areas of the code.

I find this argument unconvincing -- of course moving the codebase forward and improving it will not be done in a single large commit. Both TypeScript and Flow are rather easy to adopt incrementally, and both provide benefits immediately even before adding lots of types. Further, both of them are just JavaScript + types. Yes, there is a new thing to learn, and perhaps struggle with, but large codebases with many contributors are the exact kind that benefit most from more things being caught in an automated way, and more thorough in-code documentation.

> We also have not had many ergonomic issues with not using types yet, so the effort required to switch to a typed system currently outweighs the benefit.

As I mentioned with Prettier, the benefits of using types are typically not obvious when you haven't worked in both large untyped and typed codebases. In the end, types allow you to move faster with more confidence -- and there are always ways to subvert the system when things are too difficult to model.

**Comment by benjiwheeler** [comment]
What I'm most curious about with type checking is the edge cases where a variable is null or undefined, and in parameters/props.

But I agree with @rschamp that we'd really have to do it for all of our repos, and right now the upfront disruption is hard to justify.

**Comment by fsih** [comment]
I wouldn't mind trying some of these libraries personally. I have wasted lots of time debugging silly type issues at least a couple times, and we seem to be accumulating prop warnings in the console lately. It might be worth mentioning that our linter is already catching unused props, enforcing that JSDocs stay in sync, and rejecting PropTypes.object.

I can definitely sympathize with not wanting to add libraries without getting significant benefit from them though. When there are layers upon layers of libraries. It becomes hard to even search for what you aren't understanding because you're not sure which library it's coming from. The bar to entry for being able to understand and contribute to our code is already something that needs improvement, especially given that a lot of our contributors are very young and making their first forays into open source.
