### ISSUE TITLE
UX – Sharing Project from GUI

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-gui#3206]
### Overview
We need a UX flow for sharing projects from GUI.
**For the time being, we are going with designs for Flow 3 (below.)**

___

### Notes
While we prefer Flow 1, adding a new modal isn't in scope right now. This would definitely be the best option in the future. Will keep the sketch around for when we have time to revisit it. 

Between Flows 2 & 3, we are choosing Flow 3. Flow 3 will probably be easier to build off of in the future, and from here we can eventually move towards the UX we want.

In the meantime, we can also think about visual ways to encourage folks to fill in metadata, and also consider an "unshare" button for undo-ing accidents.

See more discussion in comments.

___

### Flow 1: Modal within GUI

Notes:
- Might formalize the share process by making it feel like you _need_ to complete these fields before you can share
- Discourage sharing without extra information (is that what we want?)

![gui share](https://user-images.githubusercontent.com/8203939/45899228-3e2c9800-bdaa-11e8-95bc-79ff5f0556bc.png)
![gui modal 1](https://user-images.githubusercontent.com/8203939/45899237-4258b580-bdaa-11e8-9632-d8eb2abf8023.png)
![gui modal 2](https://user-images.githubusercontent.com/8203939/45899239-42f14c00-bdaa-11e8-948c-fb2894aba421.png)
![gui modal 3](https://user-images.githubusercontent.com/8203939/45899240-42f14c00-bdaa-11e8-85d1-3510dc46db78.png)

### Flow 2: Redirect to Unshared Project Page

Notes:
- Safeguards you against sharing before you're ready, and also reduces need for a modal
- On the downside – does it feel redundant to hit Share twice?
- Could maybe change the language to make it clear that you're not officially "sharing" the first time you click Share in GUI?

![gui share](https://user-images.githubusercontent.com/8203939/45899289-6916ec00-bdaa-11e8-8aa7-66d056d30115.png)
![project page unshared 1](https://user-images.githubusercontent.com/8203939/45899305-70d69080-bdaa-11e8-8dac-e4dad1e0f379.png)
![project page unshared 2](https://user-images.githubusercontent.com/8203939/45899306-70d69080-bdaa-11e8-842e-59461a82d047.png)
![project page unshared 3](https://user-images.githubusercontent.com/8203939/45899307-70d69080-bdaa-11e8-927b-dda9a751e0f6.png)

### Flow 3: Redirect to Shared Project Page

Notes:
- Does it feel too sudden to share without editing description? 
- Would people feel surprised sharing without the chance to set the description?
- Need a way to communicate that your changes have been saved, and updated publicly 

![gui share](https://user-images.githubusercontent.com/8203939/45899321-792ecb80-bdaa-11e8-837c-bd2392ce57f8.png)
![project page shared 1](https://user-images.githubusercontent.com/8203939/45899323-7b912580-bdaa-11e8-9765-6acaa8d9ac90.png)
![project page shared 2](https://user-images.githubusercontent.com/8203939/45968943-5269d280-c000-11e8-9803-168864ca9fec.png)

**Comment by towerofnix** [comment]
Some notes:

* Flow 1 closely matches Scratch 1.4's sharing behavior, which looks like this:
![The "Upload to Scratch Server" dialog, prompting username/password and project name and notes (as well as tags)](https://user-images.githubusercontent.com/9948030/45906447-86f44900-bdca-11e8-9e5c-89115c9af942.png)

* Flow 3 matches Scratch 2.0 behavior.

* Several Scratchers have said that it's frustrating when they accidentally share projects.
  * [Here's one suggestion](https://scratch.mit.edu/discuss/topic/196505/), which mentions that people who are notified that the project was shared (usually from "What's Happening?" on the homepage) can view the project using [Phosphorus](https://phosphorus.github.io/) (or even the 3.0 Beta editor), even once the project is unshared.
  * [This post](https://scratch.mit.edu/discuss/topic/162844/) shows a user who accidentally shared the project three times because their drawing tablet (which works as a mouse) wasn't working.
  * [Here's another suggestion](https://scratch.mit.edu/discuss/post/432141/) for a warning. They noted that some Scratchers might find a warning prompt annoying, so they suggest there be an account option "warn before sharing?". I agree that a warning could be annoying, and even detrimental, since it could discourage users from sharing projects. But the dialog suggested in Flow 1, and used in Scratch 1.4, isn't a warning; rather, it's an extra prompt asking to fill in handy information, just in case the user forgot. But it still functions as a way to keep users from accidentally sharing projects, which is good.

**Comment by MasterOfTheTiger** [comment]
I like flow one the best. It makes it more likely for people to actually document their projects, and thus make it easier for others to understand.

**Comment by MasterOfTheTiger** [comment]
I like flow one the best. It makes it more likely for people to actually document their projects, and thus make it easier for others to understand. It might also be useful to note that you are able to edit those forms afterwards as well (for new users)

**Comment by kyleplo** [comment]
I like flow one best. Once, my 5 year old cousin accidentally shared one of my projects. This would prevent that.

**Comment by kathymakes** [comment]
Thanks for your thoughtful responses @towerofnix @MasterOfTheTiger @kyleplo , this is really helpful!

**Comment by kathymakes** [comment]
Tangential note to self: How does auto-saving work on the project page? Do keyboard shortcuts work? What is the auto-save interval?

**Comment by kathymakes** [comment]
Chatted with @carljbowman – we prefer the UX of Flow 1, but adding modal is not in scope for the time being. Will keep the sketch around for when we have time to revisit it. This would definitely be the best option, just not feasible right now.

Between 2 & 3, we were leaning towards flow 3.

In Flow 2, having to click "share" twice might be confusing for folks. (And any change in wording might not make it immediately clear.)

Flow 3 –while does have the concern of accidentally sharing before you're ready– might be easier to build off of in the future. There could be other ways to encourage scratchers to write in the metadata from this page alone.

Stay tuned.

**Comment by benjiwheeler** [comment]
+1 on Flow 1, I agree with your reasons, and I understand that the modal and its wiring will take some time to build.

Also agree on Flow 3 being the next best. Users will be able to unshare in My Stuff, so I think it's OK to make sharing quick here.

**Comment by kathymakes** [comment]
Yeah, thanks for your thoughts @benjiwheeler ! Agree that an "Unshare" button could be helpful, at least if we don't get a modal right away. I've definitely had my fair shares of unintentional shares...

**Comment by kyleplo** [comment]
Maybe also a button on the share modal to skip the instructions, it could annoy some users.
