### ISSUE TITLE
Switching sprites can take a very long time

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-gui#329]
### Expected Behavior

When I click on a sprite in the sprite selector, the editor should switch the editing target quickly (<1 second)

### Actual Behavior

On some projects, there can be a delay of >5 seconds before switching sprites even on a fast computer. During this time there is very high CPU load. On Firefox in particular, this winds up causing `TypeError: attempting to access detached ArrayBuffer` deep inside `lodash.defaultsdeep`.

### Steps to Reproduce

1. Load https://llk.github.io/scratch-gui/#144852507
2. Let the project finish loading: wait for the sprite selection panel to populate
3. Click on "Spaceship" and wait for the sprite info pane to show the "Spaceship" sprite's info
4. Click on "Ball" and wait for the sprite info pane to show the "Ball" sprite's info

### Operating System and Browser

Windows 10:
- Chrome 57.0.2987.133
- Firefox 53.0

@lifeinchords also saw this on macOS in both Chrome and Firefox

**Comment by paulkaplan** [comment]
For posterity, the big issue here is with the deep copying of sounds/costumes, what ray is working on with those linked PRs. But there is another, smaller issue that I wanted to document. 

The handle on click triggers the `blocks.jsx` containers `onWorkspaceUpdate`, which, among other things, calls `refreshSelection` on the blockly toolbox. This function takes around 100ms to execute because of the amount of text measurement going on. Another place to look when making the performance better here.

**Comment by paulkaplan** [comment]
On a large project (like this one  https://llk.github.io/scratch-gui/#155128646) the `onWorkspaceUpdate` can take **several seconds** to execute. This is a scratch-blocks issue, to be sure, or maybe we should just banish `refreshSelection`?

**Comment by paulkaplan** [comment]
Here is the flame graph of switching sprites on that large project. 
![image](https://cloud.githubusercontent.com/assets/654102/25997695/3d8ee26e-36eb-11e7-8dfa-f4d0e1ac0fb9.png)

Couple things to note:

1. The majority of the time here is in scratch-blocks (6 of 6.29 seconds worth), including a problem with creating variables that is causing repeat renders. That can be tracked in this issue https://github.com/LLK/scratch-blocks/issues/879
2. Even taking away 6 of the 6.29 seconds, we still have a reducer that takes 290ms to execute, which is far too long. We need to look into ways to reduce the amount of deep copying. I think we should start by making the data model in redux match the vm data model closer (so that we can pass data directly through).

**Comment by rachel-fenichel** [comment]
https://github.com/LLK/scratch-blocks/issues/887 captures the repeated rendering issue.  

LLK/scratch-blocks#879 is for performance optimizations within flyout.show, but the bigger problem here is the number of times it's being called.
