### ISSUE TITLE
Adding traditional Chinese to Translate extension block

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#3489]
Currently the Translate extension has Simplifed Chinese but not Traditional. Traditional Chinese is essential for educators and Scratchers from Hong Kong and Taiwan (some raised it yesterday during a J-WEL workshop). 

![image](https://user-images.githubusercontent.com/4721032/47434360-696f2200-d770-11e8-949b-82f6320a2654.png)

**Comment by Kenny2github** [comment]
Traditional Chinese is indeed used in Hong Kong, Macau, and Taiwan. I find it close to a personal insult to those living in one of those regions (including me) to exclude traditional Chinese. Though a potential question is: does the translate API support traditional Chinese?

**Comment by picklesrus** [comment]
I'm 95% sure this is a bug with some map lookups we're doing in the vm and the translation server.  It was tricky to test when we originally landed the extension because you couldn't switch your scratch language yet and I overlooked testing the languages with 4 letter codes.

Sometimes we're dropping the -CN or TW. Also, the translate api uses capital letters after the dash in the language code an scratch uses lowercase. We aren't being careful enough in the code. It should be straight forward to fix though.
