### ISSUE TITLE
About main menu 

### ISSUE THREAD

**Issue by 9ag** [LLK/scratch-gui#3580]
What's the plan to get mainmenu  done?  about the basic function(save ,redo,undo...)

**Comment by towerofnix** [comment]
The "save now" and "Save as a copy" options in the File menu are actually already completed - they do what they're expected to - but they are disabled on https://beta.scratch.mit.edu (etc) because you can't log in to your Scratch account on those sites. When Scratch 3.0 is embedded inside LLK's scratch-www repository, those options work.

I'm not sure what the plans are for undo/redo.
