### ISSUE TITLE
SVGs uploaded as costume v. sprite comes in at different sizes

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3608]
### Expected Behavior

If you import an image as a sprite it should be the same size as it would if you imported it as a costume.

### Actual Behavior

The image comes in much larger as a costume than it does as a sprite.
![itsfine](https://user-images.githubusercontent.com/1088291/47881462-94a2e280-ddfc-11e8-9d2d-39dff0ff650a.gif)

### Steps to Reproduce

Hover over the new sprite thermometer
Choose upload from file
choose an svg
Note: the new sprite is tiny on the stage
Open the costume editor
choose upload a new costume
choose the same svg
Note: the sprite now appears bigger on the stage, but the new costume is the same size in the paint editor.
select the first costume
edit it slightly
Note: the sprite gets larger on the stage
edit the second costume:
note: it stays the same size

### Operating System and Browser

Mac Chrome

**Comment by kchadha** [comment]
@paulkaplan pointed out that this is probably a bitmap resolution issue. The small version of the svg is about half the size that it is supposed to be.

cc/ @fsih, @cwillisf, @rschamp

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#777

**Comment by kchadha** [comment]
@thisandagain, I don't think this is a scratch-paint issue. The phrasing of this issue was a little bit confusing about which sprite is the problem sprite. When uploading the default cat sprite costume-1 svg as a sprite, it comes in really tiny on the stage, whereas it is the correct size in the paint editor.

It seems that this problem is now worse than before where the sprite is now coming in at 1/4 the size it should be on the stage, the costume tile reads half width and height, and the sprite selection highlight seems to correspond w/the half height / width issue.

**Comment by fsih** [comment]
@BryceLTaylor can you test if you can repro? I think this might have been fixed by https://github.com/LLK/scratch-svg-renderer/pull/60

**Comment by kchadha** [comment]
@fsih I can still repro on develop, though it's certainly not as bad as it was on beta (which is what I was testing in my previous comment):

![small-cat](https://user-images.githubusercontent.com/1786240/49169104-0fc9bc80-f307-11e8-8057-5af650ecb436.gif)
