### ISSUE TITLE
Save as Copy should save the project before making the copy

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3659]
### Expected Behavior

If you choose` file > save as copy` it should save the current project and then make a new project that is an exact duplicate of the firs tone.  This is not what 2.0 does.

### Actual Behavior

`file > save as copy` currently does not save first, so the copy can have changes that weren't made on the original.

### Steps to Reproduce

Create a project
Make some changes such as adding blocks or changing the paint editor
Before it autosaves choose File > Save as Copy
Load the original project in another window
Note: the original project doesn't have the changes you made before making the copy.

This is the current behavior in 2.0.

### Operating System and Browser

Mac Chrome

**Comment by LukeSchlangen** [comment]
I'm really interested in this issue (async stuff is always fun), but I don't think I understand the project well enough to help with this. I don't see "Save now" or "Save as Copy" in the current `develop` branch. Which branch will allow me to reproduce this error?

**Comment by benjiwheeler** [comment]
Thanks for your interest, @LukeSchlangen! Unfortunately, this is a very hard category of issue for folks in the Scratch community to help with, because it's tightly tied to the development of the Scratch website's new project page (which we're working on in a separate, internal repo).

If you're interested in learning more about how this sort of thing is being handled in scratch-gui, I recommend starting by looking at the `src/reducers/project-state.js` file, and the various `src/lib/*-hoc.jsx` files which call it.

"Save now" and "Save as Copy" are in the `src/components/menu-bar/menu-bar.jsx` file.

Hope that helps!
