### ISSUE TITLE
Sprite names handle numbers incorrectly

### ISSUE THREAD

**Issue by ethanmriley** [LLK/scratch-gui#370]
### Expected Behavior

Entering a sprite name of "sprite_1" changes sprite name to "sprite_1".
Names can be arbitrary strings of letters, numbers, and allowed special characters. 

### Actual Behavior

Entering a sprite name of "sprite_1" changes sprite name to "sprite_2".
Entering the name "sprite_2" changes sprite name to "sprite_3".
Entering "sprite_4" changes sprite name to "sprite_2".
Entering "sprite_999" changes sprite name to "sprite_2".

The number 2 is automatically appended to any letters entered; "hello" becomes "hello2".

Every number but 2 is changed to 2, except for 2 itself, which becomes 3 when a user enters a string ending in a single 2 as a new sprite name. Entering "sprite_2" when a sprite name is already "sprite_2" has no effect. 

### Steps to Reproduce

Enter any string into the name field of a sprite, and it follows this pattern. 

### Operating System and Browser

Ubuntu 16.04.1, Firefox 53.0 (64-bit)
Windows 10, Firefox 53.0.2 (32-bit)

**Comment by paulkaplan** [comment]
Interesting! Looks like two bugs combining in a strange way:

1. Hitting <kbd>Enter</kbd> seems to trigger rename twice.
2. The VM function for renaming a sprite does not filter out the name of the sprite being renamed from the list of currently used names.

Those two issues combined mean that renaming a sprite from "Cat" to "Dog" goes through this chain of events:

1. `renameSprite()` is called on "Cat" with the value "Dog", correctly renaming the sprite.
2. `renameSprite()` is called again on "Dog" with the value "Dog" (bug #1 above). Because of bug #2, the sprite is renamed to "Dog2".
