### ISSUE TITLE
On old chromebooks loops stutter

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3747]
### Expected Behavior

If you have a sprite moving around the stage in a forever loop it should move smoothly at the same rate the whole time.

### Actual Behavior

Sometimes the sprites stop moving on the stage briefly and then start moving again.  This happens periodically and seemingly randomly.

### Steps to Reproduce

Add this block stack to the cat:
<img width="180" alt="screen shot 2018-11-13 at 5 18 12 pm" src="https://user-images.githubusercontent.com/1088291/48446847-6b714300-e768-11e8-82e5-a16c006b2500.png">
Duplicate the cat
Click the green flag
Note: the cat stops and starts sometimes
Switch sprites
Note: this often causes the stuttering behavior.

### Operating System and Browser

Chrome on ChromeOS

**Comment by MasterOfTheTiger** [comment]
Switching sprites make it stutter here as well:
![peek 2018-11-13 14-57](https://user-images.githubusercontent.com/16640496/48448639-98891a00-e797-11e8-8857-9aafcac076fa.gif)

Firefox ESR on Fedora GNU/Linux 29.

**Comment by towerofnix** [comment]
@MasterOfTheTiger Same on my computer (also firefox/linux). I think it has more to do with loading the block workspace of the new sprite in that case, which is maybe somewhat expected (it's the only thing that stutters Scratch on my computer anyhow). If you just click the sprite you already have selected, so that it shows the highlight around the sprite but doesn't switch workspaces, there's no stutter.

**Comment by thisandagain** [comment]
Tracking in various other issues that look at Blockly performance and GCs.
