### ISSUE TITLE
Undoing "expand blocks" doesn't collapse fields

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-gui#387]
Don't think I can elaborate.

**Comment by rschamp** [comment]
Eventually the "Collapse blocks" menu item will be removed. Also, I actually can undo collapsing fields. It just happens one at a time.

**Comment by CatsAreFluffy** [comment]
Why?

**Comment by rschamp** [comment]
The collapse blocks feature has a high likelihood to be confusing to a significant number of Scratch users. It came in with Blockly, but was never intended to be present in `scratch-blocks`.

**Comment by LFP6** [comment]
@rschamp Apologies if the cross-post isn't desirable, but as I mentioned in https://github.com/LLK/scratch-blocks/issues/923#issuecomment-308558830, this seems counter-productive. The inability to collapse sections of code into more digestible chunks potentially makes even moderately complex code significantly confusing. Of course I assume you guys have done testing with this, but I'd encourage consideration fo "can I keep the code from being confusing" as well as "can I keep the tool from being confusing". Ideally, features can be designed so that the features aren't confusing AND improve readability.

**Comment by rschamp** [comment]
@LFP6 As I said on LLK/scratch-blocks#923 please keep discussion about the feature request on the feature request thread (LLK/scratch-blocks#391) rather than split across many issues.
