### ISSUE TITLE
FieldColourSlider: error when brightness from zero to other value

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-gui#3985]
### Expected Behavior

Block's color field slider can work well.

### Actual Behavior

Color field get unexpect color when brightness from 0 to other value.

### Steps to Reproduce

See the gif: 
![slide color](https://user-images.githubusercontent.com/15828392/49628339-8d37b000-fa1e-11e8-9090-6acc122dc90a.gif)

### Operating System and Browser

Win10 x64, Google Chrome 70.0.3538.110

**Comment by thisandagain** [comment]
@BryceLTaylor Can you repro this?

**Comment by kyleplo** [comment]
I can repro this

**Comment by joker314** [comment]
(Can reproduce on Firefox, Debian)

When duplicating the block, both blocks have a "saturation" value of 0, even though this setting was not adjusted. This explains why only greys were showing.

Moreover, if you cause this bug to happen, and then change the saturation value slightly, the colour goes back to normal.

So the "saturation" value changes unexpectedly to 0 when you set "brightness" to 0, but the "saturation" display does not change to reflect this.

**Comment by joker314** [comment]
Observations:
1. If you get into this buggy state, click away (so as to close the slider menu), and then re-open it, you notice that all the values have been zeroed, not just brightness.
2. If you duplicate the block, you get the same as observation 1.
3. If you nudge the sliders, you get that slider back to normal. For example, in the proof of concept, the colour appears grey due to the saturation being 0 (unintentionally). However, if you nudge the saturation, you get red, because red is 0. If you nudge colour, you get the correct colour and everything is good again.
4. If you instead set "saturation" to 0, rather than brightness, then brightness survives, but colour is still zeroed so you get a red.

From this, I initially thought the issue was caused by a `switch` which didn't have `break`s, because zeroing a slider would zero all the sliders above it, but leave the ones below it unaffected.

My new theory is that, internally, things are stored as hexadecimal colours (i.e., RGB), but they are specially converted into HSV just for this. My guess is that this is reversible in most cases, so everything is okay, but if you get black, then there are very many ways to reverse it back into HSV. Similarly, if you get gray, the colour value could've been anything.

If this is the case, we could internally represent everything as HSV, and only convert to RGB to _display_ the colour, and that might resolve this?

**Comment by BryceLTaylor** [comment]
I can.  I'm seeing it on Mac Chrome and Safari.

What @joker314 says is right about the saturation.  If the saturation becomes 0 the color becomes 0 (red) until you adjust it.  Similarly if the brightness ever becomes 0 the saturation becomes 0 (which in turn makes the color become 0) until you adjust it.

This causes the touching color boolean to be true on bright red, even if the color is set to some other number.

Steps to reproduce:
Create a new scratch project
Paint a new sprite
Draw a circle which has a fill of color: 0, Saturation: 100, Brighness 100
On the cat add the following stack:
![screen shot 2018-12-10 at 3 21 41 pm](https://user-images.githubusercontent.com/1088291/49759386-8794d100-fc8f-11e8-9467-a46ab62a5865.png)
Note: that color is Color: 50, saturation 100, brightness 100
Make sure the cat overlaps the red circle
Click the green flag
Change the touching color sliders so that the Color is 50brightness is 0
Change the touching color brightness to 100
Note: the cat says "not touching"
change the touching color saturation to 100
Note: that cat says touching, since it is looking for the color red, even though the sliders are set to a non-red color
