### ISSUE TITLE
Serialization/deserialization doesn't work

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#407]
To reproduce.
1. Load https://llk.github.io/scratch-gui/
2. Add the "brick wall" backdrop (or add any sprite / costume)
3. Click "Save" 
3. Reload https://llk.github.io/scratch-gui/
4. Click "Load" and choose the file you just downloaded
5. Doesn't load, there is an error in the console

```
gui.js:146209 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/4f234884958b11023d44abc010ad50ec.undefined/get/
```

That `.undefined` certainly looks suspicious. Probably has something to do with the storage change?

**Comment by DanFu09** [comment]
This happens because the dataFormat field introduced in https://github.com/LLK/scratch-storage/pull/12 by @cwillisf doesn't get saved to the JSON file.  I'm not sure where that happens, but adding that field in should fix it.  Relatedly, it seems the loading code doesn't correctly handle the case where the dataformat isn't known (the "default" behavior).
