### ISSUE TITLE
Outlines don't scale with shapes

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#4220]
### Expected Behavior

When resizing a shape, the outline should resize too.

### Actual Behavior

The outline is constant with resizing.

### Steps to Reproduce

1. Go into the vector editor
2. Add a rectangle that is small enough that you can't see the fill color.
3. Enlarge the rectangle.

### Operating System and Browser

Windows 10 on Chrome

**Comment by towerofnix** [comment]
Personally, I disagree with this suggestion (although it matches 2.0 behavior). I prefer to think of scaling as a simple way of proportionately changing a shape; if I want to treat it as truly scaling a shape up, it's not complicated to increase the outline/stroke size manually.

For the sake of discussion, what happens if the user scales the shape in only one dimension, or rather, in unequal ratio? For example, if a shape is scaled to be twice as *wide*, but to stay at the same height, how should its outline size be affected? Should it become wider but not taller? That would match the idea of stretching the shape. But personally, I've found it very rare that I want to make an outline with uneven width and height; again, I normally use the scaling tool as a way to easily adjust the shape, not exactly to *stretch* it like that.

Oh also, you should create issues related to the paint editor in https://github.com/LLK/scratch-paint. Just so you know!

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#812
