### ISSUE TITLE
Saving causes UI to pause on large projects

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4256]
### Expected Behavior

Autosave smoothly in the background, without user being bothered

### Actual Behavior

On large projects, autosaving can pause the page:

![autosave delay](https://user-images.githubusercontent.com/3431616/50699131-f0643480-1014-11e9-8d8e-5a8249448cb7.gif)

Observations:

* seems to happen before the POST request is made, judging by the text in the menu bar; so it might be that the processing we do before determining what has to save is intensive? 
* my project has 6 or so sprites, 40 or so costumes from our library, has 25 or so variables, 10 or so lists with 50 or so items total, uses cloud vars, 100-200 blocks, 10 or so of our sound library's loops. So it's big, but not that big.

### Operating System and Browser

Mac Mojave 10.14.2, Chrome Version 71.0.3578.98

**Comment by towerofnix** [comment]
This is definitely worth prioritizing because it's an issue that a *lot* of people have noticed (note that frequently users cannot save their project at all - the page goes "Aw Snap!", etc):

* [Freezes when saving](https://scratch.mit.edu/discuss/topic/329397/)
* [Save Problem](https://scratch.mit.edu/discuss/topic/329814/)
* [Freezing during autosave!!!](https://scratch.mit.edu/discuss/topic/329860/)
* [Error with saving projects](https://scratch.mit.edu/discuss/topic/329855/)
* likely [Constant Freezing](https://scratch.mit.edu/discuss/topic/329813/)
* [Project Doesn't Save, Cannot be Downloaded/Uploaded](https://scratch.mit.edu/discuss/topic/329719/)
* likely [Project won't save](https://scratch.mit.edu/discuss/topic/329655/)
* [Can't Save Project](https://scratch.mit.edu/discuss/topic/329355/)

Etc.

**Comment by benjiwheeler** [comment]
Thanks for collecting these, @towerofnix. I'm not positive the "Aw Snap!" issue is the same issue, but it certainly seems that there's a point before a save request is sent when a lot of javascript work is being done, and so it seems possible that it's the same problem.

I'm not sure there are obvious fixes -- I wonder if there are solutions people have found out there for freeing up javascript cycles for the browser, without interrupting the state of your particular javascript code. Maybe there's a way we can split up the preparatory work we do before saving and schedule it (using, say, setTimeout) so that the browser doesn't get frozen...

**Comment by paulkaplan** [comment]
I think there is some low hanging fruit here we could skim off. Looking at the performance trace for the `vm.toJSON()` method, I see a big pause due to excessive stringifying of large js objects, which also causes lots of garbage collection and memory pressure which could be causing some of the browser crashing.

We do some "defensive" stringifying/parsing in order to avoid messing with in-memory data structures, but this seems like it is causing performance problems. A first place to look would be https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb3.js#L524 Testing a few projects suggests just finding away to avoid that line could save 50% of the time `vm.toJSON` locks the UI.

@benjiwheeler you are right about queuing also, that could improve things as well, serializing one target at a time in a setTimeout. Often the majority of the code is concentrated in a single target though, so I don't have a good guess about how much that would help.

/cc @kchadha
