### ISSUE TITLE
Key [any] pressed always reports true

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#435]
### Expected Behavior

The key () pressed? block, when the key is "any" should report true **only** when a key is pressed.

### Actual Behavior

It reports true at all times.

### Steps to Reproduce

Drag out the key () pressed? block, change the key to "any", click the block and it will say "true" no matter what.
When I did this, I thought it might be detecting the mouse click, so I did:
```
when gf clicked
forever:
    switch costume to <key (any) pressed?>
end
```
and the (default) sprite switched to its first costume (i.e. true is 1, so it switched to costume number 1). To make sure this was the keypress block's problem, I did:
```
when gf clicked
forever:
    switch costume to <<> and <>> // I changed the block to a block that reports false
end
```
and it switched to its second costume (i.e. false is 0, and costume# 0 is the last costume).
### Operating System and Browser

Windows NT 10.0 Chrome 58.0.3029.110 (Official Build) (64-bit)

**Comment by Kenny2github** [comment]
Bug seems to be fixed now, <key [any v] pressed?> working normally. Closing.

**Comment by Kenny2github** [comment]
Nope, it's back now! Sprite is switching to costume number 1 whenever the block is set to "any".

I first tried
```scratchblocks
when gf clicked
forever
    switch costume to <key [space v] pressed?>
end
```
and it switched to costume1 whenever I pressed space...
then I tried
```scratchblocks
when gf clicked
forever
    switch costume to <key [any v] pressed?>
end
```
and it immediately switched to costume1 and never changed back.

**Comment by paulkaplan** [comment]
In terms of the title of this issue, "Key [any] pressed always reports true", that doesn't seem to be true any more. Here is a demo:

![key any pressed](https://user-images.githubusercontent.com/654102/32333076-5aeca070-bfbd-11e7-9e42-0556c6f70a8f.gif)

I also tried the examples you gave, and they seem to switch costumes ok?

![key any pressed - costumes](https://user-images.githubusercontent.com/654102/32333244-be3f7a80-bfbd-11e7-902f-b91c6d75f49c.gif)

If I didn't repro this correctly, or if you have a different repro for this, let me know. But I'm going to close this now because it appears to work correctly.

**Comment by Kenny2github** [comment]
yeah, it seems to come in and out...
