### ISSUE TITLE
Can't find package scratch-audio's version: 0.1.0-prerelease.20190114210212

### ISSUE THREAD

**Issue by huangjide** [LLK/scratch-gui#4399]
npm install 
 
  [18/94] Installing webpack@^4.6.0platform unsupported @babel/cli@7.2.3 › chokidar@2.0.4 › fsevents@^1.2.2 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.2.2] optional install error: Package require os(darwin) not compatible with your platform(win32)
\ [20/94] Installing resolve@^1.6.0[gh-pages@github:rschamp/gh-pages#publish-branch-to-subfolder] install gh-pages from git github:rschamp/gh-pages#publish-branch-to-subfolder, may be very slow, please keep patience
× Install fail! Error: [scratch-audio@0.1.0-prerelease.20190114210212] Can't find package scratch-audio's version: 0.1.0-prerelease.20190114210212
Error: [scratch-audio@0.1.0-prerelease.20190114210212] Can't find package scratch-audio's version: 0.1.0-prerelease.20190114210212
    at resolve (C:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:97:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.20.1

**Comment by huangjide** [comment]
⠏ [20/94] Installing eslint@^5.0.1[gh-pages@github:rschamp/gh-pages#publish-branch-to-subfolder] install gh-pages from git github:rschamp/gh-pages#publish-branch-to-subfolder, may be very slow, please keep patience
✖ Install fail! Error: [scratch-audio@0.1.0-prerelease.20190114210212] Can't find package scratch-audio's version: 0.1.0-prerelease.20190114210212
Error: [scratch-audio@0.1.0-prerelease.20190114210212] Can't find package scratch-audio's version: 0.1.0-prerelease.20190114210212
    at resolve (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:97:11)
    at resolve.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.20.1

by mac

**Comment by kamidox** [comment]
I met the same issue when I use npm mirror from https://registry.npm.taobao.org. I know that it's a nightmare if you try to use official npm repo in China. 

Here is my workaround solution:

1. Remove node_modules directory and package-lock.json if any to make sure we start form scratch: `rm -rf node_modules`. Also, you need to make sure everything is not changed, especially for `package.json` file. You can do this by typing `git status` in `scratch-gui` directory and check the result.
2. Use **official npm repo** to install scratch-audio@0.1.0-prerelease.20190114210212. For example `npm install scratch-audio@0.1.0-prerelease.20190114210212`
3. Install other scratch prerelease dependencies by using official npm repo. For example `npm install scratch-paint@0.2.0-prerelease.20190114205252 scratch-render@0.1.0-prerelease.20190122223537 scratch-svg-renderer@0.2.0-prerelease.20190110205335 scratch-vm@0.2.0-prerelease.20190123164824`.
4. Use taobao mirror to install other packages to speed up the installation process: `cnpm install`. If it's said that cnpm is not defined, refer to [https://npm.taobao.org](https://npm.taobao.org).
5. Fix peer dependencies issue. For example, if npm said `npm WARN eslint-config-scratch@5.0.0 requires a peer of babel-eslint@^8.0.1 but none is installed. You must install peer dependencies yourself.`, you can just type `npm install eslint-config-scratch@5.0.0`. Make sure to **use official npm repo again** in this time. This will avoid the taobao mirror cache.
6. After fix all peer dependencies, try `npm start`, you should see the beautiful scratch 3.0 on `localhost:8601`

PS. Here is my environment:

1. Mac OS
2. Node v10.4.0 - [Wiki](https://github.com/LLK/scratch-gui/wiki/Getting-Started#prereqs) said that we need use node 8, I am not sure it's because the Wiki is obsolete or node 10 will have some other compatibility issue. 
3. npm v6.4.0
