### ISSUE TITLE
empty bitmap costumes can't be anywhere with x > -15 or y < 15

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4409]
### Expected Behavior

If you set a sprite's position with a go to x  y block, or a move block, the sprite will go to that position

### Actual Behavior

If you set the costume to a bitmap costume that is empty, when you set its position so its x position is greater than -15 it will instead be set to -15.  Similarly, if you set the y position to be less than 15 it will instead set to 15.

It doesn't matter if you set it with a go to, a move __ steps block, or by changing x and y. 

This may have to do with the fact that empty bitmap costumes have size 480x360, but if you fill the costume with a color so it is the same dimensions it will not exhibit this behavior. 

### Steps to Reproduce

Create a new project
Open the costume editor on the cat
Add a new costume by painting it
Convert the new empty costume to bitmap
Switch to the code tab (leaving the empty costume selected)
Add a "Go To X: 0 Y: 0"
Run the "Go To x:0 Y:0" block
Note: the position of Sprite 1 in the sprite info area is now (-15, 15)
Change the values of x and y
Note: if you pick values for x less than - 15 or values of y greater than 15 it will go there, otherwise the x value will be -15 and the y value will be 15.

### Operating System and Browser

Mac Chrome

**Comment by apple502j** [comment]
Maybe #4233

**Comment by BryceLTaylor** [comment]
If the empty costume is a vector the sprite can't be positioned to x<0 or y> 1

**Comment by BryceLTaylor** [comment]
Here's another good example of this: https://scratch.mit.edu/projects/277240964/

**Comment by ktbee** [comment]
Interesting, this does indeed seem similar to the issue behind #4233 at least symptom-wise, but the forever block seems to be an important factor in this issue. This project on the develop branch can send the pen to all corners of the stage:

https://llk.github.io/scratch-gui/develop/#276971295

Though on the production site, it's limited to the bottom right quadrant instead of the top left, like #277240964 is.

**Comment by ktbee** [comment]
Taking another look at this, I realized that I had misunderstood the repro steps and my previous comment/assessment wasn't correct. I hadn't made sure that the empty costume I was looking at was a bitmap and not a vector, so never mind about the forever-loop block being a factor!

That being said, it does look like the same underlying causes as #4233. The empty bitmap's costume size is 480 x 360, which prevents use from using the [empty skin logic when setting `rotationCenter`](https://github.com/LLK/scratch-render/blob/develop/src/Skin.js#L114-L118). I'm taking a deeper look at some solutions now!

**Comment by towerofnix** [comment]
Here's a straightforward repro project, by ihgfedcba: https://scratch.mit.edu/projects/301891022/

**Comment by ktbee** [comment]
This issue was fixed by https://github.com/LLK/scratch-paint/pull/826 and https://github.com/LLK/scratch-vm/pull/2041. Going forward, empty bitmap costumes won't restrict the pen tool. For existing projects, you can fix the empty bitmap costume by converting it to a vector and then back to a bitmap. This will all these fixes to re-process the bitmap costume and fix the error.If anyone has questions on this, let me know!
