### ISSUE TITLE
I want to add a recording function in the scratch3.0 extension. What are the good suggestions or how to achieve it?

### ISSUE THREAD

**Issue by lzl525898** [LLK/scratch-gui#4533]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
You mean recording as a video right? Because 3.0 is, will be, and must not be dependent on Flash (otherwise 2.0 would go on), .flv exporting is impossible. MPEG is also difficult because of licensing issues. ogv or webm is legally easier.

`ccapture.js` (https://github.com/spite/ccapture.js/) seems to support webm. Maybe it's nice to add it, if design and performance allows.

**Comment by lzl525898** [comment]
It looks like a good choice. I'll try it. Thank you.

**Comment by JJBullet** [comment]
this looks good, ill try it out 👍
