### ISSUE TITLE
Allow extension tiles to display both internet and bluetooth requirement icons

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#4620]
This is necessary because currently the connection to Scratch Link requires a working internet connection for the initial DNS lookup.

Probably we can just put the icons next to each other with a little padding, wifi first then bluetooth (curious if @carljbowman has thoughts on this)

**Comment by evhan55** [comment]
@ericrosenbaum @carljbowman 

The current bluetooth and wifi SVGs have different inherent padding in the SVG files themselves:
![screenshot 15](https://user-images.githubusercontent.com/699840/53830477-88689680-3f50-11e9-931a-ae54f338291f.png)
![screenshot 16](https://user-images.githubusercontent.com/699840/53830483-8bfc1d80-3f50-11e9-80fb-359ff1b74a02.png)

The bluetooth SVG has good padding already without needing to add extra CSS, whereas the wifi SVGs would need some CSS.  I suggest making them match so that the CSS can be uniform for all these icons.  Any thoughts?

**Comment by evhan55** [comment]
Without making any changes to CSS or the SVG files, actually, this is how things look:
<img width="947" alt="Screen Shot 2019-03-12 at 10 09 42 AM" src="https://user-images.githubusercontent.com/699840/54206606-07108700-44af-11e9-9e3d-362afd240328.png">

@carljbowman does that look ok to you?

**Comment by carljbowman** [comment]
Sorry to the delay on responding to this. We use a standard icon square ratio for all our icons, this helps with consistency and gives us a little space to work with to optically align icons.

Before we make updates to the icon files, I'd suggest adding some margins with CSS. Might be nice to get .25rem (4px) or .5rem (8px) between the icons. The icons do feel a little tight right now.

**Comment by evhan55** [comment]
@carljbowman sounds good!
Do you have a preference here?

0.25rem:
<img width="947" alt="Screen Shot 2019-03-12 at 10 17 47 AM" src="https://user-images.githubusercontent.com/699840/54207211-25c34d80-44b0-11e9-9c80-486db29f20e6.png">

0.5rem:
<img width="950" alt="Screen Shot 2019-03-12 at 10 18 32 AM" src="https://user-images.githubusercontent.com/699840/54207253-37a4f080-44b0-11e9-9353-751dcf980f51.png">

**Comment by carljbowman** [comment]
Thanks @evhan55 - My leaning would be towards .25rem.
