### ISSUE TITLE
Add Shrink/Expand Feature to Tutorial Window

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#4670]
## Overview
We'd like to include a way to shrink (aka collapse) the tutorial window. Shrinking the UI will easier to interact with other parts of the editor and hopefully will decrease people closing the tutorial window, which has the additional side effect of losing your place in the tutorial. 

[Invision Mock / Prototype](https://projects.invisionapp.com/d/main#/projects/prototypes/16823838)

#### Tutorial Expanded View (Default view)
- A new toggle button gets added to tutorial window nav. Icon is pending.
- All buttons take on new style with icon and text stack. 

![video step](https://user-images.githubusercontent.com/3409578/54634209-1c118b00-4a58-11e9-9b4e-459294e74e78.png)

#### Tutorial Collapsed View
- The collapsed view should still be draggable
- The position in tutorial steps should be retained when collapsing. If someone is on Step 3 and collapses  the window, they should remain on Step 3 when they re-expand the window
- If there is a video, the playhead should be retained when collapsed

![collapsed view](https://user-images.githubusercontent.com/3409578/54634232-29c71080-4a58-11e9-9894-3443f50dfc39.png)

#### Dependancies
- The fencing work will have some implications on this work. 
  - We may need to play with causing some sort of reset if a window is off beyond the edge of the browser and then is expanded / collapsed.
  - If a window is collapsed we may want to limit the amount that it can exit off the top or bottom of the browser.

**Comment by evhan55** [comment]
Progress with icons:

<img width="513" alt="Screen Shot 2019-04-16 at 11 21 33 AM" src="https://user-images.githubusercontent.com/699840/56222341-d8e80f00-6039-11e9-9fd4-a4169884ea39.png">

<img width="497" alt="Screen Shot 2019-04-16 at 11 21 42 AM" src="https://user-images.githubusercontent.com/699840/56222347-dc7b9600-6039-11e9-9ecc-c5ff9094e7b4.png">

Next question is whether it's important that the 'shrink/expand' button itself changes size (and therefore width of whole header) as it changes, because the string lengths are different.
