### ISSUE TITLE
Contiguous space characters collapse to one in var/list monitors

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-gui#4823]
Not sure if this was a conscious decision, but it's been something that's niggled me about Scratch 3 since it first came out, so thought I'd bring it up and see how people respond...

### Expected Behavior

Can use spaces in variable/list values to 'pad' how it appears.

### Actual Behavior

As title.

### Steps to Reproduce

Create a variable and give it a value `"a     b"` (note multiple spaces between letters).
See that the var's monitor shows it as "a b" (only a single space between letters).

See https://scratch.mit.edu/projects/20460790/ for an example of how multiple spaces could have some degree of use. (Compare against project running within Scratch 2. Note that Scratch 2 did drop trailing spaces – not sure if that would remain a desired behaviour?)

### Operating System and Browser

N/A

**Comment by TheLogFather** [comment]
Hmmm, should've guessed the above value `"a     b"` would also get shown here as if there's only a single space between the two letters – I actually put in five spaces... :/

**Comment by paulkaplan** [comment]
> Hmmm, should've guessed the above value `"a b"` would also get shown here as if there's only a single space between the two letters – I actually put in five spaces... :/

Aha! You've inadvertently reproduced the exact bug :) In fact it is the same root cause, HTML consumes whitespace in a somewhat... unique way. In this situation, where we are trying to show what could be a pre-formatted value, we should set `whitespace: pre;` on those elements so they respect the whitespace. Definitely willing to look at a PR that implements this for monitor values.
