### ISSUE TITLE
Relationship between a sprite and its blocks workspace

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#485]
In play tests (such as our recent Catch Game external play test) we often notice that there is some confusion about the relationship between the sprite selected in the sprite pane and the blocks for that sprite in the workspace. We see:

- Not knowing that different sprites can have their own blocks
- "Where did my blocks go?" when they have changed the selected sprite
- Adding blocks to the wrong sprite or to the stage by accident

**Comment by jwzimmer** [comment]
I noticed issues like this during the Catch Game external play test (June 2017) as well.

- A user put their code in backdrop area b/c that was the area with focus (didn't notice info on cards which attempts to point out which area you should be in)
  - Then they added the apple sprite, expecting it to be associated with the scripts they had just assembled
    - They were expecting the apple sprite to be added to the active scripts rather than expecting they would have to add scripts to the active sprite
  - They said “It just started the whole thing over!” because the scripts “disappeared” when the script area switched focus
- A user put scripts for the catcher in the apple workspace along with the apple scripts
  - They then said “this is not working” and didn't have any idea where to start troubleshooting
    - When comparing the stack they assembled to the cards, it looked the same; trouble-shooting work they have done outside of the blocks is a little trickier to realize is even something you might need to do
  - The project wasn't working b/c their bowl stack was in the apple workspace, and nothing was in the bowl workspace
  - They hadn't made the connection between what the blocks act on and what workspace they are in
    - Maybe they were just seeing the blocks as executing on the entire project, and missing the piece where you have to associate the blocks with a specific asset somehow; could we surface this necessity better?

**Comment by mrjacobbloom** [comment]
I liked how in Scratch 1.x, the sprite-info area was above the scripts area, which might've helped clear up this kind of confusion:
<img width="189" alt="screen shot 2017-07-11 at 12 44 48 pm" src="https://user-images.githubusercontent.com/2879020/28084756-e489fc5a-6636-11e7-8add-b006abe5536d.png">
In Scratch 2.0, a translucent picture of the sprite appears over the scripts area to remind users which sprite they're editing:
<img width="61" alt="screen shot 2017-07-11 at 12 45 07 pm" src="https://user-images.githubusercontent.com/2879020/28084798-03004266-6637-11e7-8dce-82c8da0b249e.png">
The 2.0 style doesn't seem as noticeable since it's less prominent and not required for any kinds of interactions

**Comment by jwzimmer** [comment]
During the Extension Categories External Playtest (8/3/17), we saw users deleting a sprite without realizing that they would also lose a recording or block stacks associated with that sprite. This was exacerbated by the as-yet lack of undo functionality. We saw that sprite hierarchy remains unclear (that a sprite is selected, that it contains blocks and assets).

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#24
