### ISSUE TITLE
Replace tutorial videos with thumbnails on "offline" platforms

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#4895]
When loading tutorials on an "offline" platform (e.g. Scratch Desktop, Scratch for Android) we would like to replace the initial video with the tutorial thumbnail (as shown in the tutorial library) as to avoid situations where the video fails to load when internet access is either unreliable or unavailable. 

We feel that this is an important enhancement to have in place prior to the start of Africa Code Week (https://africacodeweek.org/). While the event is not until October, the Africa Code Week team has requested that our materials be delivered by the end of June in time for the start of teacher training which means that we would want to have this landed, tested, and released before the end of this iteration.

/cc @ntlrsk @kosiecki @carljbowman

**Comment by cwillisf** [comment]
Can we do some fancy JavaScript stuff to make it so that we initially load the thumbnail and then if possible replace the thumbnail with the video? If we can, should we?

For that matter, if it's reasonable to do the above we might want to do that even for the normal, online version of Scratch since it make the tutorials more robust against (for example) the video provider being down. On the other hand, maybe we don't want this feature in "offline" versions: I could see someone objecting to it if they're trying to reduce data charges.

**Comment by thisandagain** [comment]
@cwillisf I most certainly feel like this is something we may want to consider long-term. @paulkaplan and I also talked about perhaps including the videos as an option in a preferences pane somewhere. I think we should file something to track these potential paths for enabling users of the Desktop, Android, and iOS editors to access the videos when they have access to the internet.
