### ISSUE TITLE
Trouble with nesting ifs

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#502]
In play tests we have seen multiple instances of kids making errors like this one, in which an if block is unintentionally nested inside another if block (it should be a sequence of two separate if statements):

<img width="336" alt="screen shot 2017-07-06 at 10 30 52 am" src="https://user-images.githubusercontent.com/567844/27916160-3a7340fe-6236-11e7-993b-e5dd3b6b4b93.png">

Maybe the nesting could be visually clearer somehow, to make the fact that the blocks are nested more obvious.

**Comment by mrjacobbloom** [comment]
Zebra striping a la Snap!
<img width="93" alt="screen shot 2017-07-06 at 10 06 27 am" src="https://user-images.githubusercontent.com/2879020/27920744-d2b55950-6232-11e7-8993-b1faa415d0f3.png">

**Comment by liam4** [comment]
Indeed, zebra striping makes it very clear when you aren't following a screenshot or video correctly!

**Comment by jwzimmer** [comment]
I also saw confusion around control loops during the Catch Game External Playtest (June 2017):
- Distinguishing forever, if, and if else in the blocks menu
- At least 2 users were confused due to nested instead of sequential "if" loops as in @ericrosenbaum's screenshot
- A user didn’t realize they needed to wrap an if statement in a forever statement to get the stack to trigger every time the if statement was true

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#19
