### ISSUE TITLE
Implement Tips

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#525]
### Expected Behavior

_A small tips window should appear showing tips about scratch_

### Actual Behavior

_Not Implemented_

### Steps to Reproduce

_Open llk.github.io/scratch-gui_

### Concept/Example Userscript

![tips](https://user-images.githubusercontent.com/17478432/28045726-db7c3770-65ac-11e7-98f3-563e5fc040ce.PNG)

#### Userscript
[Scratch Tips.user.zip](https://github.com/LLK/scratch-gui/files/1137401/Scratch.Tips.user.zip)

**Comment by liam4** [comment]
Hm, having it be a (pretend) popup window in your concept is interesting! Being able to drag it around the UI is definitely handy.

* You don't want it on top of the paint editor while you're painting something.
* You probably want it nearby your scripts while you're copying a script.
* You might want to move the window while you're browsing the media library, so that it's easier to find the same asset used in an example. (Btw, I think the tips window should appear above popup dialogs.)

**Comment by thisandagain** [comment]
Hi @TheBrokenRail. Thanks for thinking about this. We are rethinking the help and onboarding for Scratch 3.0 and hope to share more towards the end of the year. In the meantime I'm going to close this. Thanks.
