### ISSUE TITLE
Error when import Scratch-gui to Reactjs project

### ISSUE THREAD

**Issue by huylh97** [LLK/scratch-gui#5300]
![Screenshot from 2019-11-15 20-53-37](https://user-images.githubusercontent.com/28486635/68948302-2f911380-07ea-11ea-8371-a50bba76c8c5.png)
![Screenshot from 2019-11-15 20-53-07](https://user-images.githubusercontent.com/28486635/68948304-2f911380-07ea-11ea-92e6-f0cfb32ce0aa.png)

How can I import Scratch-gui to my reactjs project to use it as a component?
Like this: <GUI>

**Comment by apple502j** [comment]
Is your disk full? Also, try npm run build and see if it works

**Comment by HoangHuyLe** [comment]
Thank you very much because you alway reply my question.
I had fixed "no space left on device" and run npm run build.
But it has new error follow this.
![Screenshot from 2019-11-15 21-21-46](https://user-images.githubusercontent.com/28486635/68950182-3752b700-07ee-11ea-9b42-0384f16b2cc3.png)

How can I fix this Error?
If you don't mind, please give a different contact channel like Facebook or Slack or something else.
I am building a E-learning programming Scratch in VietNam. It will help Scrathc.mit.edi expend user.
Please help me.
Thank you very much.

**Comment by apple502j** [comment]
You should buy more high-spec computer with more disk space and memory.

**Comment by uwpdver** [comment]
Enter this command at the command line:
**export NODE_OPTIONS=--max_old_space_size=4096**
