### ISSUE TITLE
Sprites are positioned slightly "off" while dragging

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5507]
### Expected Behavior

When you click on a sprite for long enough to drag it in the editor, it should start dragging but should not move at all until you move your mouse.

### Actual Behavior

When you drag a sprite in the editor, it moves one pixel up and to the left. When you stop dragging it, it moves back down and to the right:

![Peek 2020-03-12 11-00](https://user-images.githubusercontent.com/25993062/76535070-ae245780-6450-11ea-8f79-69c2a075527d.gif)

### Steps to Reproduce

1. Enter the editor
2. Hold down the left mouse button on top of a sprite until a shadow appears (this means the sprite is being dragged)
3. Observe how the sprite shifts slightly

### Operating System and Browser

All

**Comment by BryceLTaylor** [comment]
This is by design

**Comment by adroitwhiz** [comment]
Are you sure about that? The precise offset depends on the stage border width, which points to a bug. If you increase [`$stage-standard-border-width` in `units.css`](https://github.com/LLK/scratch-gui/blob/develop/src/css/units.css#L16), the sprite will move more when dragged.

**Comment by adroitwhiz** [comment]
![Peek 2020-03-17 12-07](https://user-images.githubusercontent.com/25993062/76876154-e90afe80-6847-11ea-93c2-644d3dc05c49.gif)

**Comment by adroitwhiz** [comment]
@BryceLTaylor Can you confirm that despite the strange stage-border behavior and the lack of this in previous versions of Scratch, this is still a design feature? It strikes me as something that would hinder Scratchers from positioning sprites the way they intend to.

**Comment by fsih** [comment]
@paulkaplan

**Comment by benjiwheeler** [comment]
@carljbowman @kathymakes can you confirm that this UX is intended?

**Comment by adroitwhiz** [comment]
Confirmed that this wasn't intentional--going to continue to look into ways to communicate that sprites have been "picked up"

**Comment by carljbowman** [comment]
Thanks @adroitwhiz for looking into this. 

Here are some additional notes from the design meeting: 
- There is a balance between maintaining the understandability that something is picked up and providing precision. 
- The visual feedback that something is being dragged is shown as a drop shadow and possibly the sprite becoming slight off set, if the later was intentional. We may be able to communicate that something is being dragged by just using a drop shadow.
- Blocks have a drop shadow to communicate they are being dragged, they do not shift their position slightly when "picked up". As an additional visual cue on platforms with a cursor, the cursor changes based on hover and drag states.
- The sprite shifting position as apart of the visual feedback was not in 2.0, which likely points as this being a bug as @adroitwhiz pointed out.
