### ISSUE TITLE
Implement variables "for this sprite"

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#559]
### Expected Behavior

* When creating a variable there should be a way to indicate that it is "for all sprites" vs. "for this sprite"

**Comment by paulkaplan** [comment]
Thanks @Kenny2github. We now have a `develop` branch that is ahead of the master (stable) branch. You can find it https://llk.github.io/scratch-gui/develop/. The delete option is there in the dropdown 
![image](https://user-images.githubusercontent.com/654102/28524855-32078ae2-7050-11e7-9ab0-b15e87f6a913.png)

I'm going to edit the description a little bit to reflect that, so we can use this issue just to track the global/local variable feature request.

**Comment by liam4** [comment]
> so we can use this issue just to track the global/local variable feature request.

Well, then..

I think there should be some sort of separation between local and global variables, in the variable palette. In [my Scratch mod](https://liam4.github.io/scrap-mod/), I did that, so, simple concept images:

![Variable palette screenshot](https://user-images.githubusercontent.com/9948030/28545989-7aa50b9a-709f-11e7-813c-2bb69d1854b1.png)

![Variable dropdown menu screenshot](https://user-images.githubusercontent.com/9948030/28545992-7c060156-709f-11e7-838b-f65a3826599a.png)

In my own Scratch projects, I have to name variables "self.(name)" or "global.(name)" so that they're all grouped together by the alphabetical sorting:

![Variable palette screenshot](https://user-images.githubusercontent.com/9948030/28546102-e6a7a956-709f-11e7-8e80-2e5b45f83b06.png)

It would be nice if they were automatically grouped together by the Scratch editor, instead.

**Comment by kyleplo** [comment]
Why can't you have "for stage only" variables?

**Comment by hedgehog125** [comment]
Maybe it could have a symbol next to it to indicate it's local? Not sure what though.

**Comment by mrjacobbloom** [comment]
There's some discussion of that kind of thing in LLK/scratch-blocks#1379

**Comment by Craig88** [comment]
Am I right in thinking the current develop branch version (https://llk.github.io/scratch-gui/develop/) is still missing this feature? I notice there is a "More Options" with a "We're working on it" message.

**Comment by paulkaplan** [comment]
Implemented!
