### ISSUE TITLE
[Regression] say balloon goes to the wrong place first time a project is played (with some costumes)

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#5647]
### Expected Behavior

Click the green flag on a project - the "say" balloon should stay in the same place each time you click the green flag. 

### Actual Behavior

The say balloon jumps down the first time the project plays, then goes to the correct place when clicking green flag again. 

### Steps to Reproduce

For example, click green flag on this (unshared) project: https://scratch.mit.edu/projects/385454623/
First time the say balloon jumps. The second time (and subsequent times after that) it behaves as expected. Reload the project to see the issue again. 

Note that the problematic costume is just a duplicate of the costume that works fine. You can duplicate "natalie low arm" that works fine - and switching to the duplicated costume will display this problem (if you reload the project).

Same with this project with a different drawing that's a remix:
https://scratch.mit.edu/projects/385033373/

### Operating System and Browser
Mac OS 10.146 , Chrome: 80.0.3987.163

**Comment by BryceLTaylor** [comment]
I can get this to happen every time by:
Create a new project
Drag out 2 "when green flag clicked" blocks
To one attach a "Say hello for 2 seconds" block
To the other attach a "Switch to costume2" block
Save
Reload
Click the green flag
Note: the flag starts at the center of the costume.

It only happens if you switch to a different costume (not the same one) and use a say block on at the same time
