### ISSUE TITLE
Fit the layout into 1024px wide without scrolling

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#579]
### Expected Behavior

_Please describe what should happen_

We want the full scratch-gui layout to fit into a screen 1024px wide (standard tablet width). 

### Actual Behavior

_Describe what actually happens_

The block editor is fixed at 600 and the stage is fixed at 480, plus 2 8px gutters = 1098px to fit the entire layout. 

@carljbowman we need to decide what to make smaller and by how much. Taking down the stage to 85% of it's size (to 408px) should allow the blocks+stage+gutters to fit. If we do that, we need to do two things:

- [ ] Make the stage component resilient to changing size on the fly, and making sure the drag events are properly scaled (non-obvious, need to pair with @cwillisf or @rschamp on this).
- [ ] Figure out how to get the sprite info panel to fit by either shrinking or hiding some of the items (name, x, y, rotation, direction, visibility, ...).  Implementing that part will be easy, but I'll need design guidance on it.

**Comment by rschamp** [comment]
When we scale down the stage, we should take care to check out pixel art projects, and choose a size that scales nicely for them, since many may depend on the exact proportions to look good.

**Comment by Kenny2github** [comment]
I noticed this earlier - because the GUI is a bit too wide it allows scrolling on an iPad - and since the “add sprite” and “add backdrop” buttons seem to be `position:fixed` they stay in place while the GUI scrolls, meaning that they’re out of place occasionally. I took a small screen recording, but I currently don’t have access to a pc so I can’t put it here yet - I will post it when I can.
