### ISSUE TITLE
Integration tests are failing: "This version of ChromeDriver only supports Chrome version 80"

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5790]
### Expected Behavior

Integration tests should pass

### Actual Behavior

The [latest build](https://travis-ci.org/github/LLK/scratch-gui/builds/689094574) failed twice in Travis due to ChromeDriver throwing `SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 80`.

**Comment by adroitwhiz** [comment]
@rschamp I think I saw this error in the CircleCI build logs when that was still enabled but this is the first time I've seen it on Travis. Any idea what's up with this?

**Comment by apple502j** [comment]
This may be why: https://github.com/LLK/scratch-gui/blob/develop/.travis.yml#L5 says it installs stable version of Chrome, and chromedriver is pinned to 80 on package-json: https://github.com/LLK/scratch-gui/blob/develop/package.json#L47

Maybe you can pin both or bump Node and chromedriver.

**Comment by Smrman** [comment]
**Scratch users** will always be r**unning the latest stable Chrome release** because of its auto-update mechanism, so it's better to **reflect that with Travis** imo, and thus run the latest stable Chrome version. This implies the `ChromeDriver` package should **not be pinned to a specific version**.

I'd recommend allowing major releases updates in the `package.json` file for the `ChromeDriver` package.

https://github.com/LLK/scratch-gui/blob/884843fb82afd28255494fe26bed0beb959ae6fc/package.json#L47

Fix:
```json
"chromedriver": "*", 
```

**Comment by matschaffer** [comment]
I found a bit of a workaround for this. You can download older chromium builds from https://chromium.cypress.io/

Then modify selenium-helper.js to launch the downloaded copy of chromium

```
import {Options} from 'selenium-webdriver/chrome';

...

        const options = new Options()
            .setChromeBinaryPath('/Applications/Chromium.app/Contents/MacOS/Chromium');

        this.driver = new webdriver.Builder()
            .forBrowser('chrome')
            .withCapabilities(chromeCapabilities)
            .setChromeOptions(options)
            .build();
```

It's a bit roundabout but it allows running the integration suite on older chrome versions without having to downgrade your main Chrome.app.

**Comment by matschaffer** [comment]
https://github.com/LLK/scratch-gui/pull/8146 fixes this

@BryceLTaylor or @kchadha, mind closing it out?

**Comment by rschamp** [comment]
Yup, thanks @matschaffer!
