### ISSUE TITLE
You can type the character e or E into numeric block

### ISSUE THREAD

**Issue by martinohanlon** [LLK/scratch-gui#6007]
### Expected Behavior

Blocks with numerical input should only allow numbers to be entered.. e.g. `Move (10) steps`

### Actual Behavior

You can type the letter `e` or `E` into a numerical input into Scratch blocks

![image](https://user-images.githubusercontent.com/2329501/87784660-a164a580-c82e-11ea-829b-f4622ed1d165.png)

I couldnt find any other characters which were excepted.

### Steps to Reproduce

1. Drag a `Move (10) steps` block into the code area.
2. Enter `e` or `E` as number of steps 

### Operating System and Browser

Windows 10, Chrome & Scratch Desktop

**Comment by apple502j** [comment]
WAI?
[![Image from Gyazo](https://i.gyazo.com/b2546c11148ba2cc6a989e9b5d7bf80a.gif)](https://gyazo.com/b2546c11148ba2cc6a989e9b5d7bf80a)

**Comment by Kenny2github** [comment]
You can type (case insensitive) "e" for **e**xponential notation - 1e2 means 1×10<sup>2</sup>. The only really weird part is that you can type "e" on its own.

**Comment by BryceLTaylor** [comment]
I believe it only validates the input at the character level, not whether the final input is a valid number.  If you couldn't type an e on its own, you wouldn't be able to follow it with an exponent. The blocks behave as expected when an invalid number is used (move block doesn't move, etc.).  This is by design.
