### ISSUE TITLE
How can I embed scratch editor in my project?

### ISSUE THREAD

**Issue by ghost1998** [LLK/scratch-gui#6105]
I want to use scratch in my next js app with my own authentication and storage mechanisms. I am unable to find documentation related to this. I was able to find an [old issue](https://github.com/LLK/scratch-gui/issues/695) that said they were going to add support, but it was unattended. 

Is there any way I can embed scratch editor on my website and use my own custom backend for storage? 

Apologies if this was answered elsewhere. Thank You in Advance.

**Comment by apple502j** [comment]
Well, the project page is open-sourced so you can look at the source code. Maybe [project-view.jsx](https://github.com/LLK/scratch-www/blob/develop/src/views/preview/project-view.jsx)?

Note that you also need to build backend API because scratch-gui is intended for front-end only. Backend API is closed source but not hard to make - look at L954 + https://github.com/LLK/scratch-gui/blob/develop/src/lib/storage.js

**Comment by rschamp** [comment]
I think @apple502j has answered this as sufficiently as we would be able to!  By configuring the storage, you can use any source for project json, assets, and/or sb3 files.
