### ISSUE TITLE
The GUI + default project should be able to run offline

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#617]
### Expected Behavior

_Please describe what should happen_
While offline, starting the GUI should work.

### Actual Behavior

_Describe what actually happens_
The GUI attempts to load the assets for the default project JSON, but requires a network connection for these.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Open the GUI without a network connection

**Comment by thisandagain** [comment]
Related (and likely will have the same resolution) but the target (iOS webview) I’m deploying to does have network access, but for some reason loading the default empty project does not result in any targets being added to the runtime.

I have tried stepping through the code in a debugger. It seems to me that the `sb2.parseScratchObject` function completes correctly, but then something goes wrong with the promises, because the `.then` in `VM.fromJSON` never runs.

**Comment by aeons** [comment]
Let me know if you need more details, and I'll try digging a bit deeper.

**Comment by TheBrokenRail** [comment]
I think this would become a lot easier when the SB3 format is finalized (not just json but compression and loading assets from file) so it just loads a default SB3 file instead of loading the assets manually

**Comment by gengshenghong** [comment]
It may be the time to think about finalizing the SB3 format as the scratch-painter project is started, without the support of embedding assets into SB3, it is not possible to support saving/loading of painted costumes, I guess. Usually this will be saved as base64 data in json. We can just play with the painter now, but not really use it in project.

Not sure whether there is a timeline to finalize SB3, after that, some commonly used features like "taking picture as costumes", "upload local file as costumes" should be supported easily.

**Comment by rschamp** [comment]
@aeons Note that this is closed in a tad hacky way. But hopefully the hack works for you in the interim!
