### ISSUE TITLE
Try to prevent you from messing up your project by saving over your assets with question mark assets

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#6539]
Sometimes we have bugs that cause users' projects to be broken because costumes have turned into question marks. Often these projects are salvageable because the server still has all the data from when the project was working, and you can just wait for the client to get fixed. But if the user changes anything in their project, there's no way for them to recover the working version of the project on their own.

When we load a project where we've converted costumes into question marks, the client could do something to try to prevent this. Maybe when you try to save it can say hey, some of your assets seem to be broken. Are you sure you want to save? Maybe when we load the question mark asset, we can save the original version of the asset as metadata, in case it becomes readable in the future and we can switch back to it.

**Comment by adroitwhiz** [comment]
I think this should be prioritized. A recent asset server outage caused many SVG costumes to not load, and because the question mark asset overwrites the original, this resulted in a huge amount of permanent data loss for Scratchers:

![image](https://user-images.githubusercontent.com/25993062/114171173-e7ecb980-9901-11eb-8acf-d3630e1e7680.png)
