### ISSUE TITLE
Should disabled buttons have a "pointer" cursor?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#663]
### Expected Behavior

When moving the mouse over a disabled button (e.g. the undo/redo buttons in the sound editor when no changes have been made), the cursor icon doesn't change to a pointer.

Though - I'm not certain if this is actually expected behavior.

### Actual Behavior

The cursor icon changes to a pointer.

### Steps to Reproduce

The undo/redo buttons in the sound editor are an example of disabled buttons (actually, they're the only buttons which may be disabled found in the GUI at all?).

### Operating System and Browser

Firefox 52.2.0 on Debian Linux (testing).

**Comment by joker314** [comment]
I think that the "pointer" cursor is an indication to the user that an item is clickable. As such, it should only be shown when clicking on an item will cause an action to occur.

That isn't the case with disabled buttons, since they won't do anything, so I think it's a good idea to not switch to the "pointer".

I don't know though.

**Comment by thisandagain** [comment]
@carljbowman Thoughts on this one?

**Comment by DeleteThisAcount** [comment]
Should not change into the like ready to click, it should stay normal because it might confuse people to think that's clickable

**Comment by Kenny2github** [comment]
I think it shouldn't change to a pointer - the button can't be clicked, why show that it can?

**Comment by carljbowman** [comment]
Good catch. I agree that we could be a bit more intentional in regards to UI elements that are disabled vs inactive. Maybe there is better language for these states, but here are some examples.

Disabled example: the case of Undo / Redo, in which an action (e.g. Undo) is 'disabled' due to state of the editor, the cursor should not change. 

Inactive example: the case of Show / Hide, in which the UI is showing a toggled 'active' and 'inactive' state (e.g. Show active / Hidden inactive) due to state of the sprite, the cursor should change to the pointer on both elements.
