### ISSUE TITLE
Scratch does not change language into Spanish

### ISSUE THREAD

**Issue by Freddyqt** [LLK/scratch-gui#679]
### Expected Behavior

Change language of Scratch

### Actual Behavior

Does not change the language, when I select Spanish. The interface is maintained.

### Steps to Reproduce

Hi friends, I've followed this tutorial https://github.com/LLK/scratch-gui and managed to get scracth on a server

The problem is that it does not change the language, as I show in the following image.

**Comment by Kenny2github** [comment]
Hi @Freddyqt! Translations are not implemented yet - the translators need to get to work. The translating capability is there solely for testing purposes. Therefore, the language does not change. When translations have been completed, then the language change will take effect. Thanks!

**Comment by Freddyqt** [comment]
Hi @Kenny2github , how could you help to translate the scratch interface?

I'd like to help!

**Comment by chrisgarrity** [comment]
@Freddyqt yes, as @Kenny2github said, the translations are not implemented yet, and we haven't opened it up to all the translators because we're still working on the infrastructure. The current menu is a prototype, and I'm in the middle of changing how it gets translations. If you'd like to help get the gui translated, you could help with https://github.com/LLK/scratch-gui/issues/527. That's needed so we can put the strings to be translated into the translation system. It's not really worth having translators do their work until we have a more complete set of things to translate.
