### ISSUE TITLE
Remote code execution and other vulnerabilities

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-gui#6889]
When you clone the repository and run `npm install`, npm finds 1055 vulnerabilities. They should be fixed as there are vulnerabilities like remote code execution.

**Comment by apple502j** [comment]
In most cases they can be ignored, as these don't affect Scratch itself.

Commenting through all production dependency "vulnerabilities":
- 2 RCEs for serialize-javascript, but doesn't affect Scratch as source code is static.
- 2 DoS for node-fetch, but doesn't affect Scratch since it's only for server-side rendered React.
- 15 Prototype Pollution for minimist but doesn't affect Scratch as the code is for building tools.
- 97 Validation Bypass for kind-of but doesn't affect Scratch as they are all called from building.
- Again, a DoS for node-fetch but doesn't affect Scratch.
- 2 more vulnerabilities that only affect build process.

**Comment by ghost** [comment]
Ok, sorry.
