### ISSUE TITLE
How do I embed Scratch-GUI in my project?

### ISSUE THREAD

**Issue by tarr11** [LLK/scratch-gui#695]
I would like to embed a "Scratch GUI" component in my existing ReactJS project, and then customize the load / save behavior to save from my database.

Is there a guide or example for doing this kind of thing?

**Comment by thisandagain** [comment]
Hi @tarr11. Because Scratch 3.0 is still incomplete we haven't written documentation yet (we have it on the schedule for the end of the year). For this specific use case I would recommend taking a look at the API in `scratch-storage` which includes the concept of pluggable "backends" to allow switching between different datasources.

**Comment by ghost1998** [comment]
Is there any update on this?
