### ISSUE TITLE
npm-published packages should follow semver

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-gui#7138]
### Expected Behavior

Scratch projects published to npm should use semver version numbers >= 1.0 so that dependents can control when to accept breaking changes.

### Actual Behavior

This repository uses "prerelease" version numbers like `0.1.0-prerelease.YYYYMMDDhhmmss` which contain no information about breaking changes.

**Comment by apple502j** [comment]
1) What is considered "breaking"? For example, is removing camera upload breaking? Or is it just for technically incompatible builds?
2) Won't this make things to get outdated easily? scratch-storage is a good example; it's not updated in WWW because newer version includes breaking changes, and nobody bothered to review.

**Comment by ghost** [comment]
An idea, similar to semantic versioning but similar that this repo could use: The patch version number is incremented every time a version of Scratch Desktop or the Scratch version on the main website is released, and the minor number is incremented every time either of the above two apply and a significant new feature is added. The major number could stay constant, possibly at 3.
