### ISSUE TITLE
Dragging clones confuses the sprite indicator panel

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#721]
### Expected Behavior

When dragging a clone of a sprite, the sprite indicator panel (or whatever it's called) should display the stats of the parent sprite

### Actual Behavior

It displays its name as "Name", its x position as "x", its y position as "y", its show/hide status as neither, its direction as "", and (interestingly enough) its rotation style identical to its parent's style when it was cloned.
However, showing/hiding the clone still works, and does affect that particular clone, though the indicator has no reaction.

### Steps to Reproduce

1. Get a sprite
2. Clone it a few times
3. Drag the sprite off its clones, and drag the clones around
4. Play around with the stats (if you can)

### Operating System and Browser

Raspbian Desktop Chrome 57

**Comment by towerofnix** [comment]
>When dragging a clone of a sprite, the sprite indicator panel (or whatever it's called) should display the stats of the parent sprite

Says you :)

Why not have it just properly display the stats of the clone itself? After all, you're dragging the clone - not the parent.

Note that in Scratch 2.0, scripts themselves are shared between a parent and its clones, but when you have a clone selected (by dragging it or selecting info from the context menu), manually clicking on a script will run the script on the clone, not the parent sprite. (This is especially handy because you can easily inspect the variable values of a clone by clicking on the variable blocks in the palette while the clone is selected.

So there *is* a good amount of benefit to selecting a clone. It's not entirely obvious when a clone is selected or not, though; the only way to tell is that when a clone is selected, *no* sprite icon in the sprite list is selected. Might be worth considering how to make it more apparent that a clone is selected. (Though selecting clones is probably an obscure feature, anyways.)

**Comment by towerofnix** [comment]
I just thought - maybe display " (Clone)" next to the name field? Or even "Clone" instead of "Sprite" next to the name field.

**Comment by DeleteThisAcount** [comment]
Display Clone of (sprite name)
