### ISSUE TITLE
Implement Pen extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#725]
We are moving the pen blocks to an extension. 

This will include changes to the way pen color is set: https://github.com/LLK/scratch-blocks/issues/1091

**Comment by towerofnix** [comment]
My first instinct is "whoaa hold on, does this mean that pen blocks will be less discoverable??", and, while that may be true, I wonder if moving blocks to their own extensions will make users *more* interested in them..

In any case, I'm curious as to what the actual rationale for moving Pen blocks to an extension is?

**Comment by mrjacobbloom** [comment]
I assume it's because Scratch's core functionality is more about simple games with moving sprites, and pen is just as specialized as some of the other stuff they're putting into extensions

**Comment by DeleteThisAcount** [comment]
Hmmm... Does this mean that users will need the extention before they open up a project or....

Proper extension support!!!!!

**Comment by ericrosenbaum** [comment]
@DeleteThisAcount the plan is that projects containing extensions will automatically load them. It's gonna be cool!

**Comment by kyleplo** [comment]
Speaking of extensions, could you consider adding extensions from scratchx.org and http://savaka2.github.io/scratch-extensions-directory/ as non-experimental extensions?

**Comment by ericrosenbaum** [comment]
@kyleplo we're excited about the possibilities for extensions for Scratch 3.0! We're working on figuring out how to make a system for them that includes all the flexibility and power of scratchx (and maybe even more!), but keeps extensions safe, reliable and understandable for everyone. The plan is still evolving...

**Comment by brianharvey** [comment]
May I vote no on this change?  I know my ideas might be considered suspect, given that I think kids can even understand λ, but I've never understood the idea that if a kid doesn't understand everything on the first day, s/he'll be scared off.

This discussion used to be held in the context of the List blocks.  There was some reluctance about them, back in the day, for the same reason: 8-year-olds won't understand them.  And they don't, not on day one, but they don't get scared off, and they _want to learn!_  Watch an 8-year-old on day one of playing a new video game.  S/he doesn't understand _anything_— figuring out how the game works is the whole fun of it.  If kids were scared of things they don't understand, they'd never learn how to walk, or ride a bike.

I've never shown any kid of any age a squiral without him/her wanting to know how to do it.  They never say, "oh, I don't understand this, I think I'll give up on Scratch."

It took _years_ to talk you guys into custom blocks.  Did anyone quit Scratch because of them?

I mean, yes, being welcoming to beginners is more important than pushing the limits.  But it's not either/or.  And the whole reason for the different palette colors is that having another palette doesn't make the other palettes more crowded.  That was the point of the Events palette, right?  Make Control less crowded?  But nobody said "let's make hat blocks be something you have to load an extension to see."

And, you know, there's all those decades of accumulated Logo teaching experience that you're turning away from.

P.S.  I _do_ like the part about Hue, Saturation, etc.  But it seems to me that once you're expecting people to have "saturation" in their vocabulary, you might as well make the range 0-255.

**Comment by breenworks** [comment]
I am totally with Brian on this.  I have observed tens of thousands of workshop participants over the past several years utterly delighted by the discovery/use of Pen blocks within their first hour of using Scratch. Also brings to mind the excitement Andrea Meyr's TurtleStitch and Eric's BeetleBlocks have generated with conference demo crowds.

Humble suggestion: if you must eliminate the Pen category, could you place a basic set of Pen blocks in the Looks category (where you currently have other blocks which change the appearance of the Backdrop)? Or you could at least include a classic, top-down turtle sprite in the Scratch Sprite Library which contains all the Pen blocks, if you will allow sprites to load extensions (vs. having to open an outside project).

p.s. I find Clone and Broadcast blocks confound new users far more than Pen blocks, but surely hope those will remain firmly in place, too.

**Comment by SillyInventor** [comment]
Lowering the floor is good and, with the extension, it shouldn't lower the ceilling signficantly. However, it's unclear how much this lowers the floor, and I am concerned about breaking projects and curriculi while alienating current students and teachers.

**Comment by Kenny2github** [comment]
@SillyInventor the plan is, as per above, that projects with pen blocks will automatically load the pen extension.
This lowers the floor, but still doesn't lower the ceiling.

**Comment by thisandagain** [comment]
@brianharvey While we agree that there is significant value in the "Pen" blocks, we also know from user studies and usage data that they aren't used as much as many other parts of Scratch and often when they are, they are correlated with decreased retention. We see an opportunity in focusing the experience a bit and putting some features (like "Pen" and even some of our more advanced "Music" features) into extensions where we can push the walls and ceiling of these tools even further without as much worry about eroding the beginner experience. This is something we are looking forward to testing over the next several months and if it doesn't work we'll roll it back (just like we do with everything else in 3.0).

@breenworks and @sillyinventor We are not removing the pen blocks. We are moving them to an extension in Scratch 3.0 which we expect will give them even *more* visibility when kids are ready. All existing projects that use pen with automatically load this extension and continue to function normally.

**Comment by griffpatch** [comment]
I actually can agree with this idea... scratchers already like to
categorise projects as 'pen' projects.
It also might allow for extra pen features to be added? We originally hear
talk of pen text blocks?
Another nice feature that would make many peoples lives better would be a
pen filled polygon tool :)
Ok - since I brought that up, how about this idea - A textured polygon
using the current sprite's costume as the texture? ok... maybe I've gone
too far now - he he.

**Comment by SillyInventor** [comment]
@thisandagain I understand that the pen blocks will be accessible and it's good to know that the current break in pen projects will not persist. I am not sure about the assertion that pen will be more visible as it's behind two additional clicks. I suspect differences in retention with pen are curriculumn specific, as we've observed the reverse. We're making mods for 3D and 1st class functions etc. anyways, it is not much work to expose pen initially for some teachers. Sorry for the over reaction, I was just surprised when undergrads doing play tests started complaining. That's what I get for not paying more attention to the repo.

@griffpatch I agree pen text would be useful. I see a lot of students loading in each letter costume by hand and making 'typewriters' to get text one the screen. We've had a number of undergrads get irritated and write their own code to do just that.

**Comment by PullJosh** [comment]
> We can push the walls and ceiling of these tools even further without as much worry about eroding the beginner experience.

Absolutely love this choice. :+1: It's the perfect compromise between beginner accessibility and full-featuredness. As @griffpatch mentioned, a few additional (more complex) pen options would be *awesome* for advanced users, and would no longer interfere with beginners.

---

Question: Will Scratch extensions still be designed to be tinkered with by the community? It would be *awesome* to have community-created extensions available in the library, but I am a *bit* concerned that it could be difficult to justify placing user-created extensions directly alongside (what used to be) Scratch's core functionality (pen blocks).

Once option to consider might be including two separate sections in the extension selection dialoge: "official" extensions and "community created" ones. Of course, even community created extensions would still need to be carefully curated by Scratch Team members, but it could be a nice way to feature more polished extensions while still allowing for experimental ones.

**Comment by brianharvey** [comment]
So, I like the part about not worrying about advanced features confusing new users.  Does that mean you'll put in first class lists and first class procedures as an extension?

**Comment by mrjacobbloom** [comment]
> Question: Will Scratch extensions still be designed to be tinkered with by the community? It would be awesome to have community-created extensions available in the library, but I am a bit concerned that it could be difficult to justify placing user-created extensions directly alongside (what used to be) Scratch's core functionality (pen blocks).

> Once option to consider might be including two separate sections in the extension selection dialoge: "official" extensions and "community created" ones. Of course, even community created extensions would still need to be carefully curated by Scratch Team members, but it could be a nice way to feature more polished extensions while still allowing for experimental ones.

Ooh what about crowdsourcing it? Let the community review community extensions and if they get enough votes/whatever the ST can take a look at curating them (sorry I'm getting ahead of myself, but I've wanted official support for community extensions for a long time)

**Comment by thisandagain** [comment]
@brianharvey LOL. I knew you were going to go there. I can't commit to anything, but these are exactly the types of things that we think extensions will afford us to explore.

**Comment by thisandagain** [comment]
@PullJosh @mrjacobbloom Strong support for community created extensions is a major interest for us. There is still a ton of work to do to make that possible, but it is absolutely on the roadmap.

**Comment by bob1171** [comment]
@mrjacobbloom That would be AWESOME!

**Comment by ghost** [comment]
Is the source code for the pen extension public?

**Comment by apple502j** [comment]
yes https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_pen/index.js
