### ISSUE TITLE
Add realtime collaboration

### ISSUE THREAD

**Issue by VeryUsual** [LLK/scratch-gui#7355]
You need to add real-time collaboration so people can see other people dragging the blocks around in real time!

**Comment by Samq64** [comment]
I'm pretty sure this is rejected. Here's the quote from The Official List of Rejected Suggestions on the Scratch forums:
>__2.1 Adding users to work on projects__
Having multiple Scratchers work on the same project would be difficult to moderate not only due to technological limitations but also because it could lead to private messaging; for more information, see 7.1 on this list.  This suggestion includes live editing (similar to Google Docs) and other forms of private collaboration.  If you would like to work on a project with another Scratcher, you can remix each others' projects.
>
>At the moment, a turn-based collaboration system for shared projects is NOT rejected; you can discuss it on [this topic](https://scratch.mit.edu/discuss/topic/322107/).

**Comment by BryceLTaylor** [comment]
Thank you @Samq64, that is correct.
