### ISSUE TITLE
Categories scrollbar covers blocks

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#755]
It's hard to read the blocks

![topblocks](https://user-images.githubusercontent.com/2855464/31460542-d1c63f38-ae94-11e7-8918-983b9825a5fe.png)

Chrome/Edge on Windows. On Firefox the scroll bars cover the categories.

**Comment by gbonanome** [comment]
I can confirm the issue also on other browsers for MacOS Sierra 10.12.5. It's related on how different browser deal with overflow and scrolling.
I attach some screenshots (Safari has no problem because is the only one that does not overflow content vertically) :

Chrome | Firefox | Safari
------------ | ------------- | -------------
Version 61.0.3163.100 | Version 56.0 (64 bit) | Version 10.1.1
<img width="187" alt="schermata 2017-10-12 alle 13 28 16" src="https://user-images.githubusercontent.com/1076656/31493909-7a92d51a-af51-11e7-8488-df17988659c8.png"> | <img width="169" alt="schermata 2017-10-12 alle 13 28 28" src="https://user-images.githubusercontent.com/1076656/31493932-888438da-af51-11e7-91db-43be796ca215.png"> | <img width="237" alt="schermata 2017-10-12 alle 13 28 34" src="https://user-images.githubusercontent.com/1076656/31493937-8be0889e-af51-11e7-9ca7-d333288b9be4.png">

**Comment by Kenny2github** [comment]
Duplicate (again) of LLK/scratch-blocks#1119

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1119
