### ISSUE TITLE
SVG thumbnails disappear/ cut in half

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-gui#762]
### Expected Behavior

When loading a 2.0 project in 3.0 sprite thumbnails should look the same. 

### Actual Behavior

Some of the thumbnails for SVGs are either missing or cut in half

### Steps to Reproduce

See example project:
In 2.0 : https://scratch.mit.edu/projects/26818098/#editor
In 3.0: https://llk.github.io/scratch-gui/#26818098

### Operating System and Browser

Mac OS Chrome 61

**Comment by paulkaplan** [comment]
@thisandagain @cwillisf so the problem here is that the raw SVGs have the wrong viewbox/width height info. The renderer re-renders the SVG to measure the real bounding box, and uses that. I think it makes sense for the thumbnails of your sprite / costume to do the same thing (since those SVGs can come from anywhere, user-generated etc), but with the library thumbnails I think we should just feed all of the costumes through the render resizer and re-upload the assets, so that we don't have to be doing that on the client whenever they open the asset library. If so, can we split this into two separate issues, one to fix the SVGs in the library and one to use the renderer's svg-renderer on the sprite/costume thumbnails?

**Comment by thisandagain** [comment]
Agreed. I can take the library side if @cwillisf doesn't mind taking the renderer side of this.

**Comment by cwillisf** [comment]
Sounds good to me. I haven't worked with SVGs-as-files much... is there an ImageMagick-like tool (or maybe IM itself?) that could do this as a command-line batch kind of thing? Just for future reference :)

As for using the renderer's svg-renderer: any objections to making that a separate module and referencing it from both the GUI and the renderer? The SVG code doesn't really have much to do with WebGL...

**Comment by thisandagain** [comment]
@cwillisf I think I can probably script this without too much trouble.

**Comment by paulkaplan** [comment]
no objections, but would also be fine with exporting the svg-renderer as a property of RenderWebGL so it can imported into the GUI as `import {SvgRenderer} from 'scratch-render'`. Also a tip: the `CostumeCanvas` component is the relevant code in the GUI.

**Comment by amazinigmech2418** [comment]
I saw this before. For some reason the same thing happens in phosphorus.
