### ISSUE TITLE
Do we need a "reset pen" block OR should "set pen color to [color]" reset the transparency?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#771]
This question came up during an internal smoketest on 10/11/17. We had noticed that setting the pen to a new color seemed to re-set the hue value but not the saturation & brightness values.

### Steps to Reproduce

Add the pen extension, then try using the pen and adjusting the color parameters, and re-setting the color.

### Operating System and Browser

Chrome, Mac, at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/

**Comment by quat1024** [comment]
(somewhat unrelated, and probably something you've talked about, but) having a reset pen block/function might be nice, just so that it's not possible to make the pen completely transparent, forget you did, then wonder why you don't see anything when you do "pen down"!

maybe it's valuable to include transparency right alongside the HSV sliders, too? would make the options in the "set pen [property v] to ( )" block match one-to-one with the properties you can set manually with the color picker.

**Comment by towerofnix** [comment]
Note you can already set a transparent pen by passing a number in the format of `0xAARRGGBB` (instead of `0xRRGGBB`) to the set-pen-to-color block (even in 2.0), so you wouldn't need to change the format of the value in the color input - just adding another slider which would change the `AA` part would be enough.

**Comment by thisandagain** [comment]
After some discussion the thought was that this might introduce more confusion than it resolved. That said, we are excited to see how we might be able to improve the visibility of pen "state" while exploring options for indicators / monitors for extensions post preview release.
