### ISSUE TITLE
Clicking on blocks doesn't run them

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#799]
This may need to move to either scratch-blocks or scratch-vm, but logging here until we figure out the source of the issue.

### Expected Behavior

_Please describe what should happen_
When I click on a block, either in the palette or on the workspace, it should run. When I click on a reporter, it should report its value

### Actual Behavior

_Describe what actually happens_
When clicking on a block, the cursor appears to momentarily drag the block, and it doesn't run. Only when clicking stacks with hats, do the blocks in the stack run.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
1. Visit llk.github.io/scratch-gui/develop
2. Click <kbd>move 10 steps</kbd>
3. Observe that the cat does not move 10 steps, it just sits there, smugly

### Operating System and Browser

Chrome 61 and Safari 11, Mac OS 10.12 (probably all browsers)

**Comment by towerofnix** [comment]
Note also that the block doesn't need to be in the palette; it won't work even if it's in the script area. Clicking on the block doesn't make it glow, like expected, either.

Also, of this script..

![when this sprite clicked / move 10 steps / repeat 10 { start sound meow / wait 0.1 secs }](https://user-images.githubusercontent.com/9948030/31826841-83cfaf4a-b58c-11e7-97f3-3c5181e22f21.png)

..clicking on any block, *except* the hat block, ran the script (and the whole script glowed, like expected). Clicking on the hat block did nothing.

**Comment by paulkaplan** [comment]
It seems to be related to some of the recent changes to how scratch-blocks updates the toolbox / deals with workspace updates. We disable events on workspace refresh (because we clear / repopulate the workspace, we don't want to hear about delete/create events during that). However workspace refresh was recently changed to also cause a toolbox refresh, and the VM was relying on those events. That change will soon be reverted from scratch-blocks, but there will definitely be more cleanup involved.
