### ISSUE TITLE
Dev question: node version and dependency upgrade status

### ISSUE THREAD

**Issue by matschaffer** [LLK/scratch-gui#8000]
Hi, I was interested in contributing so I got a clone of the project going.

I was a little surprised to find the tests running on node 10 https://github.com/LLK/scratch-gui/blob/develop/.circleci/config.yml#L43 which hit EOL last year and security EOL 9 months ago (https://endoflife.date/nodejs)

Additionally there are a fair number ([91](https://github.com/LLK/scratch-gui/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies)) of dependency upgrade PRs open.

Do you need any help testing upgrades? I could help verify the changes, but I'll need a partner with merge access to make the merges.

**Comment by rschamp** [comment]
The version of node usually doesn't affect the results of our tests, since this is a client-side library. But if you would like to take a stab at upgrading that in our CI we'd welcome a PR for that. We're aware of the large number of open dependency PRs and are enlarging our team partially to deal with the maintenance burden.

**Comment by matschaffer** [comment]
Great thanks @rschamp ! I’ll open an issue to upgrade the CI node to something recent.
