### ISSUE TITLE
Click to select a character, add the position is random

### ISSUE THREAD

**Issue by X2431** [LLK/scratch-gui#8015]
I hope it can appear in a fixed position after clicking, but setting xy coordinate is invalid. Please give me some suggestions  
![image](https://user-images.githubusercontent.com/42490553/155101232-3b3575c7-c46b-45c3-9a8e-e70c11be7c84.png)

**Comment by rschamp** [comment]
It's by design for sprites added from the library to appear in a random position. We don't plan to support sprites to be added into a fixed position, but you could modify this part of the gui for yourself if you wanted to: https://github.com/LLK/scratch-gui/blob/ba76db7350bd43b79119cac2701bc10f6c511f0c/src/containers/sprite-library.jsx#L30
