### ISSUE TITLE
Add Project Loading State

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#827]
Currently there is not loading state when loading a project from JSON or from ID. 

For reference, 2.0 has the loading bar that includes some meta data (n/x Asset), but we should have a little more fun with CSS animation.

**Comment by mrjacobbloom** [comment]
A mockup of a few ideas that may come in handy: https://scratch.mit.edu/projects/159757800/

**Comment by carljbowman** [comment]
Quick follow up. There were some technical concerns regarding the block rendering impacting an animation. Depending on the amount of blocks being rendered, this could cause a delay (aka a "ca-chunk") of varying lengths in the loading sequence . Larger projects with larger delays may appear to have failed loading. But...

@paulkaplan and I made a quick prototype using CSS transforms and keyframes to create animations that were unaffected by the block rendering. It's important that these animations only alter CSS properties that do not effect browser layout. For example: using transforms like `translateY` instead of positioning like `top`. 

All in all, CSS animations look like a viable option for providing seamless feedback during the loading sequence.

**Comment by towerofnix** [comment]
@carljbowman I'm just a little confused on the "message content" section of your post - obviously those don't add up to 100%.

I assume specific messages like "Creating blocks" and "Loading (sprites, sounds, backdrops, extensions)" would only be shown when those specific processes are happening. But what happens if these are happening at the same time (e.g. downloading costumes and sounds at the same time)? How does the loading screen choose which to show, and when does the message change (e.g. from "downloading costumes" to "downloading sounds")?

**Comment by paulkaplan** [comment]
@towerofnix I think the idea was that they are weighted relative to each other, so for example the first one is 50x more likely than the bottom one. 

We will be able to separate out the load process into more steps in the future, but right now it'll just choose one for the entire process.
