### ISSUE TITLE
Asset Server Documentation

### ISSUE THREAD

**Issue by ShipmasterKyle** [LLK/scratch-gui#8413]
I'll keep this brief. There is no documentation for setting up an asset server or really any server on Scratch forks. Some guide on how to do so or addendum to the wiki would be appreciated.

Most developers won't face this issue due to not many actually messing with assets. Many devs simply want to mess around with features or patch bugs but a lot of people will fork scratch-gui to make their own IDE. One of the best examples is Turbowarp. Many devs would like to build off of the work scratch has done to create an entirely new product or experience for users. Assets play a major part in how the IDE works and thus its crucial to have some amount of documentation that goes further than how to make a local clone of the project.

**Comment by cwillisf** [comment]
Thanks for your interest! I'm afraid this is an area that we aren't able to support. Our asset management system is specific to our infrastructure setup (servers and services, etc.) so it's not likely to be useful to others, and if we were to start over we'd probably do it differently anyway. We also just don't have the capacity to support others who are trying to mimic our servers, especially since we change them over time. Finally, we'd like to avoid providing any assistance to those who would like to abuse our systems, since we have enough problems with that already!

Instead of replicating our asset servers, I recommend providing an alternative implementation of `scratch-storage`, or even just alternative "helpers" for use with your own asset management system. That way you can manage assets in whatever way works for you, and you don't need to buy or emulate the same services we use. You can find an example of an alternative storage helper in the `scratch-desktop` repository here: [ElectronStorageHelper.js](https://github.com/LLK/scratch-desktop/blob/develop/src/common/ElectronStorageHelper.js)
