### ISSUE TITLE
Blurry sprites

### ISSUE THREAD

**Issue by sergi0g** [LLK/scratch-gui#8875]
I am trying to create a project with a world map. When trying to import a bitmap of it, it is automatically cropped to a size that fits the stage (480x360). That is a too low resolution for me. I have also tried importing a vector image ~7000 px wide. That results in me unable to zoom the sprite more than the stage size. If I try zooming on another costume and then switch to the map, it appears blurry, especially in full screen. I know you've had this problem before and that you reverted the fix. 

However, what part of the code would I change to either:
- Disable the 480x360 limit
- Make the vector render correctly

Please help me, because I don't have a lot of time left to finish this project.

**Comment by CST1229** [comment]
1. You could use something like [TurboWarp](https://turbowarp.org/), enable the HD image uploads addon (in the Addons menu in the menubar), upload the image with the HD Upload button and export the image and reimport it into Scratch. (Also, the bitmap size limit is actually 960x720)
3. Vector images have limited sizes ([2048x2048](https://github.com/LLK/scratch-render/blob/develop/src/SVGSkin.js#L7) maximum) because textures cannot be infinitely large, and to prevent crashing lower-end devices (like mobile). (Also, if you didn't know, vector images are converted into a bitmap when being rendered.)
