### ISSUE TITLE
Should the sound editor play the sound on undo/redo?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#927]
The sound editor plays the sound each time you press one of the effects buttons.

Should it also play the sound when you press the undo or redo button?

**Comment by thisandagain** [comment]
This was something @quachtina96 and I were discussing WRT accessibility, but in addition I've seen kids be surprised / frustrated upon hitting undo/redo as the waveform change can be fairly subtle.

**Comment by quachtina96** [comment]
Outside of accessibility, I expected the sound to be played so that I could easily confirm that the effect of undo or redo had been applied. Given that the effects buttons (slower, faster, echo etc) play the resulting sound aloud, playing the sound upon redo/undo would be consistent. 

With the lens of accessibility, the audio feedback would be helpful since you would otherwise have to hit the play button again to play the sound and confirm it's what you want.

**Comment by carljbowman** [comment]
Agreed. This seems like a great idea! As both of you expressed the visual feedback on the waveform is nuanced and easy to miss. Simply hearing the audio change based on your actions feels more consistent, but also more concrete that the visual representation. 👍
